<?php echo $this->render('date-commission/partials/header.phtml') ?>

<form class='form-horizontal' method='post' >

    <div class='pull-right' >
        <a class='btn btn-default' href="<?php echo $this->url(array('id_commission' => $this->commission['ID_COMMISSION'], 'id' => $this->datecommission['ID_DATECOMMISSION']), 'datecomm', true) ?>">Annuler la modification</a>
        <input type='submit' class="btn btn-success" value='Sauvegarder'>
    </div>

    <h2>Modification de la fiche de la date de passage en commission</h2>

    <div class="form-group">
        <label class="col-sm-3 control-label">Libellé</label>
        <div class="col-sm-9">
            <input class='form-control' type='text' name='LIBELLE_DATECOMMISSION' value='<?php echo $this->datecommission["LIBELLE_DATECOMMISSION"] ?>' />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">Type d'évènement</label>
        <div class="col-sm-9">
            <select class='form-control' name='ID_COMMISSIONTYPEEVENEMENT'>
                <?php foreach( $this->DB_typesevenements as $item ) : ?>
                    <option value='<?php echo $item["ID_COMMISSIONTYPEEVENEMENT"] ?>' <?php if( $item["ID_COMMISSIONTYPEEVENEMENT"] == $this->datecommission["ID_COMMISSIONTYPEEVENEMENT"] ) echo "selected" ?> >
                        <?php echo $item["LIBELLE_COMMISSIONTYPEEVENEMENT"] ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

</form>
