<?php echo $this->render('date-commission/partials/header.phtml') ?>

<div id='commission'>
    <div class='pull-right' >
        <a class='btn btn-default' href="<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), "comm_calendrier") ?>">Revenir sur le calendrier <?php echo $this->commission['LIBELLE_COMMISSION'] ?></a>
        <a class='btn btn-default' href="<?php echo $this->url(array('id_commission' => $this->commission['ID_COMMISSION'], 'id' => $this->datecommission['ID_DATECOMMISSION']), "datecomm_edit") ?>">Modifier la fiche</a>
        <a class='btn btn-default' href="<?php echo $this->url(array('id_commission' => $this->commission['ID_COMMISSION'], 'id' => $this->datecommission['ID_DATECOMMISSION']), "datecomm_edit_odj") ?>">Modifier l'ordre du jour</a>
    </div>

    <h2>Informations générales</h2>

    <h3>
        Ordre du jour
        <a class='btn btn-primary btn-sm pull-right' style='margin-top: -2px;' href='<?php echo $this->url(array(), 'message_add', true) ?>'>
            <i class='glyphicon glyphicon-export'></i>
            Exporter l'ordre du jour par membre
        </a>
        <a class='btn btn-primary btn-sm pull-right' style='margin-top: -2px; margin-right: 2px;' href='<?php echo $this->url(array(), 'message_add', true) ?>'>
            <i class='glyphicon glyphicon-export'></i>
            Exporter le CR type de l'ordre du jour
        </a>
    </h3>

    <?php if( count($this->odj) > 0 ) : ?>
        <ul class="list-group">
            <?php foreach($this->odj as $dossier) : ?>
                <li class="list-group-item">
                    <?php if($dossier['VERROU_DOSSIER'] == 0) : ?>
                        <span class="badge"><i class='glyphicon glyphicon-unchecked'></i> En attente de validation ...</span>
                    <?php else : ?>
                        <span class="badge" style="background-color:#8eb571"><i class='glyphicon glyphicon-check'></i> Dossier validé</span>
                    <?php endif ?>

                    <span><i class='glyphicon glyphicon-time'></i> 15h00 à 16h00 : </span>
                    
                    <?php if(array_key_exists('ID_ETABLISSEMENT', $dossier) && $dossier['ID_ETABLISSEMENT'] != null) : ?>
                        <strong>
                            <a href="<?php echo $this->url(array('id' => $dossier['ID_ETABLISSEMENT']), 'ets', true) ?>"><?php echo $dossier['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?></a>
                        </strong>
                    <?php endif ?>

                    <?php echo $dossier['LIBELLE_DOSSIERTYPE'] . ' - ' . $dossier['LIBELLE_DOSSIERNATURE'] ?> (<a href="<?php echo $this->url(array('id' => $dossier['ID_DOSSIER']), 'doss', true)?>">Voir le dossier complet ...</a>)
                </li>
            <?php endforeach ?>
        </ul>
    <?php else : ?>
        <p class='muted'><small>Aucun dossier lié à cette date de commission.</small></p>
    <?php endif ?>

    <h3>
        Membres concernés
        <a class='btn btn-primary btn-sm pull-right' style='margin-top: -2px;' href='<?php echo $this->url(array(), 'message_add', true) ?>'>
            <i class='glyphicon glyphicon-export'></i>
            Exporter les PV types
        </a>
        <a class='btn btn-primary btn-sm pull-right' style='margin-top: -2px; margin-right: 2px;' href='<?php echo $this->url(array(), 'message_add', true) ?>'>
            <i class='glyphicon glyphicon-export'></i>
            Exporter les convocations
        </a>
    </h3>

    <?php if( count($this->membres_concernes) > 0 ) : ?>
        <?php foreach($this->membres_concernes as $membre_concerne) : ?>
            <h4>
                <?php echo $membre_concerne['LIBELLE_COMMISSIONMEMBRE'] ?>
                <small class='muted'>
                    <?php if($membre_concerne['presence'] == 0) : ?>
                        Membre obligatoire
                    <?php elseif($membre_concerne['presence'] == 1) : ?>
                        Membre facultatif
                    <?php elseif($membre_concerne['presence'] == 2) : ?>
                        Membre pour information
                    <?php endif ?>
                </small>
            </h4>
            <div class='row'>
                <?php foreach($membre_concerne['membres'] as $contact) : ?>
                    <div class='col-sm-4'>
                        <?php echo $this->partial('components/contact.phtml', $contact) ?>
                    </div>
                    <?php if(!isset($i)) $i = 1; else $i++; ?>
                    <?php if($i == 3) : ?>
                        </div> <div class='row'>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
        <?php endforeach ?>
    <?php else : ?>
        <p class='muted'><small>Aucun membre n'est concerné par cette date de commission.</small></p>
    <?php endif ?>

</div>
