<form class="form-horizontal" method='post' enctype='multipart/form-data' >

  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class='modal-title'>Ajouter une pièce jointe</h4>
      </div>

      <div class="modal-body">

        <div class="form-group">
          <label class="col-sm-3 control-label">Libellé</label>
          <div class="col-sm-9">
            <input type='text' name='name' class='form-control' />
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Fichier</label>
          <div class="col-sm-9">
            <input type='file' name='file' class='form-control' />
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Mise en avant ?</label>
          <div class="col-sm-9">
            <ul class='list-unstyled'>
              <li><input type='radio' name='mise_en_avant' value='0' checked >Seulement dans la liste principale</li>
              <li><input type='radio' name='mise_en_avant' value='1' >Afficher l'image dans le diaporama</li>
              <li><input type='radio' name='mise_en_avant' value='2' >Afficher l'image dans les plans</li>
            </ul>
            <p class='muted'><small>Uniquement pour les images.</small></p>
          </div>
        </div>

      </div>

      <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Annuler</a>
          <input type='submit' id='submit' value='Ajouter' class='btn btn-success' />
      </div>

    </div>

  </div>

</form>
