<?php echo $this->render('etablissement/partials/header.phtml') ?>

<div class='pull-right' >
    <a class='btn btn-default' href="<?php echo $this->url(array('action' => 'edit-contacts')) ?>">Gestion des contacts</a>
</div>

<h2>Contacts</h2>

<?php if(count($this->contacts_etablissements_parents) > 0) : ?>

	<h3>Contacts des établissements parents</h3>
	<div class='row'>
	<?php foreach($this->contacts_etablissements_parents as $contact) : ?>
		<div class='col-sm-4'>
			<?php echo $this->partial('etablissement/partials/partial-contact.phtml', $contact) ?>
		</div>
		<?php if(!isset($i)) $i = 1; else $i++; ?>
		<?php if($i == 3) : ?>
			</div> <div class='row'>
		<?php endif ?>
	<?php endforeach ?>
	</div>

<?php endif ?>

<?php if(count($this->contacts) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de contact.</p>
        <p><a href='<?php echo $this->url(array('action' => 'edit-contacts')) ?>' class='btn btn-default btn-large'>Ajouter un contact</a></p>
    </div>

<?php else : ?>

	<?php if(count($this->contacts_etablissements_parents) > 0) : ?>
		<h3>Contacts de l'établissement</h3>
	<?php endif ?>
	<div class='row'>
	<?php foreach($this->contacts as $contact) : ?>
		<div class='col-sm-4'>
			<?php echo $this->partial('etablissement/partials/partial-contact.phtml', $contact) ?>
		</div>
		<?php if(!isset($i)) $i = 1; else $i++; ?>
		<?php if($i == 3) : ?>
			</div> <div class='row'>
		<?php endif ?>
	<?php endforeach ?>
	</div>

<?php endif ?>
