<?php echo $this->render('etablissement/partials/header.phtml') ?>

<div class='pull-right' >
    <a class='btn btn-default' href="<?php echo $this->url(array('controller' => 'dossier', 'action' => 'add', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>">Ajouter un dossier</a>
</div>

<h2>Liste des dossiers</h2>

<?php if(count($this->visites) == 0 && count($this->etudes) == 0 && count($this->autres) == 0) : ?>
    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de dossier.</p>
        <p><a href='<?php echo $this->url(array('controller' => 'dossier', 'action' => 'add', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>' class='btn btn-default btn-large'>Ajouter un dossier</a></p>
    </div>
<?php else : ?>

<div id="content_visites_ets">
<?php if( count($this->visites) > 0 ) : ?>
    <h3>Visites</h3>
    <ul class='search-list'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->visites); ?>
    </ul>
<?php endif ?>
</div>

<div id="content_etudes_ets">
<?php if( count($this->etudes) > 0 ) : ?>
    <?php if( count($this->visites) > 0 ) echo "<hr />"; ?>
    <h3>Études</h3>
    <ul class='search-list'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->etudes);  ?>
    </ul>
<?php endif ?>
</div>

<div id="content_autres_ets">
<?php if( count($this->autres) > 0 ) : ?>
    <?php if( count($this->visites) > 0 || count($this->etudes) > 0) echo "<hr />"; ?>
    <h3>Autres</h3>
    <ul class='search-list'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->autres);  ?>
    </ul>
<?php endif ?>
</div>
<?php endif ?>
