<form id='etablissement' class="<?php echo $this->add ? 'add' : 'edit' ?>" action='<?php echo $this->url(array('action' => $this->add ? 'add' : 'edit')) ?>' method='post' >

    <?php if($this->add) : ?>
    <div class='pull-right' >
        <input type='submit' class="btn btn-success" value="Ajouter l'établissement">
        <input type="hidden" name="date" value='<?php echo date("Y-m-d H:i:s") ?>'>
    </div>
    <h3>Ajout d'un établissement</h3>
    <?php else : ?>
    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?php echo $this->url(array('action' => 'index')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>
    <h3>Modification de l'établissement</h3>
    <?php endif ?>

    <div class='row-fluid'>

        <!-- Informations générales de l'établissement -->
        <div class='span6'>
            <h4 class='h4_subtitle'>Général</h4>
            <div>
                <input style='width: 100%; box-sizing: border-box; height: 2.5em;' type='text' placeholder="Libellé de l'établissement" name='LIBELLE_ETABLISSEMENTINFORMATIONS' value='<?php if ( $this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"] ) echo htmlspecialchars($this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES) ?>' />

                <dl class='dl-horizontal'>
                    <!-- Numéro d'identification -->
                    <dt>Identifiant</dt>
                    <dd>
                        <div>
                             <input type='text' name='NUMEROID_ETABLISSEMENT' id='NUMEROID_INPUT' value='<?php echo $this->etablissement['general']["NUMEROID_ETABLISSEMENT"]?>' />
                        </div>
                    </dd>

                    <!-- Statut de l'établissement -->
                    <dt>Statut</dt>
                    <dd>
                        <select name='ID_STATUT' <?php if (!$this->is_allowed_change_statut) echo "readonly" ?>>
                            <?php foreach( $this->DB_statut as $item ) : ?>
                                <option value='<?php echo $item["ID_STATUT"] ?>'
                                    <?php if($this->etablissement && $item["ID_STATUT"] == $this->etablissement['informations']["ID_STATUT"]): ?>
                                        selected
                                    <?php elseif (!$this->is_allowed_change_statut): ?>
                                        disabled
                                    <?php endif ?>
                                >
                                    <?php echo $item["LIBELLE_STATUT"] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </dd>
                </dl>
            </div>

            <h4 class='h4_subtitle'>Classement</h4>
            <dl class='dl-horizontal'>
                <dt>Genre</dt>
                <dd>
                    <select name='ID_GENRE'>
                        <?php foreach( $this->DB_genre as $genre ) : ?>
                            <option value='<?php echo $genre["ID_GENRE"] ?>' <?php if( $genre["ID_GENRE"] == $this->etablissement['informations']["ID_GENRE"] ) echo "selected" ?> >
                                <?php echo $genre["LIBELLE_GENRE"] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </dd>

                <dt class="champ_icpe champs">ICPE ?</dt>
                <dd class="champ_icpe champs">
                    <p>
                        <input type='hidden' name='ICPE_ETABLISSEMENTINFORMATIONS' value='0' />
                        <input type='checkbox' name='ICPE_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["ICPE_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> />
                    </p>
                </dd>

                <dt class="champ_categorie champs">Catégorie</dt>
                <dd class="champ_categorie champs">
                    <select name='ID_CATEGORIE'>
                        <?php foreach( $this->DB_categorie as $item ) : ?>
                            <option value='<?php echo $item["ID_CATEGORIE"] ?>' <?php if( $item["ID_CATEGORIE"] == $this->etablissement['informations']["ID_CATEGORIE"] ) echo "selected" ?> >
                                <?php echo $item["LIBELLE_CATEGORIE"] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </dd>

                <dt class="champ_classement champs">Classement</dt>
                <dd class="champ_classement champs">
                    <select name='ID_CLASSEMENT'>
                        <?php foreach( $this->DB_classement as $item ) : ?>
                            <option value='<?php echo $item["ID_CLASSEMENT"] ?>' <?php if( $item["ID_CLASSEMENT"] == $this->etablissement['informations']["ID_CLASSEMENT"] ) echo "selected" ?>>
                                <?php echo $item["LIBELLE_CLASSEMENT"] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </dd>

                <dt class="champ_famille champs">Famille</dt>
                <dd class="champ_famille champs">
                    <select name='ID_FAMILLE'>
                        <?php foreach( $this->DB_famille as $item ) : ?>
                            <option value='<?php echo $item["ID_FAMILLE"] ?>' <?php if( $item["ID_FAMILLE"] == $this->etablissement['informations']["ID_FAMILLE"] ) echo "selected" ?> >
                                <?php echo $item["LIBELLE_FAMILLE"] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </dd>

                <dt class="champ_classe champs">Classe</dt>
                <dd class="champ_classe champs">
                    <select name='ID_CLASSE'>
                        <?php foreach( $this->DB_classe as $item ) : ?>
                            <option value='<?php echo $item["ID_CLASSE"] ?>' <?php if( $item["ID_CLASSE"] == $this->etablissement['informations']["ID_CLASSE"] ) echo "selected" ?> >
                                <?php echo $item["LIBELLE_CLASSE"] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </dd>

                <dt class="champ_periodicite champs">Périodicité (en mois)</dt>
                <dd class="champ_periodicite champs">
                    <div>
                        <input type='number' class="input-small" name='PERIODICITE_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["PERIODICITE_ETABLISSEMENTINFORMATIONS"] ?>' />
                    </div>
                </dd>
            </dl>

            <h4 class='champ_types champs h4_subtitle'>Activités <a href='#' style='font-size: 0.85em; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_types_activites_secondaires').clone().appendTo( $('#activite_ul') ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); $('#activite_ul li:last select').change(); return false;">Ajouter un type et une activité secondaire</a></h4>
            <dl class='dl-horizontal champ_types champs'>
                <!-- Type et activités -->
                <dt>Types & activités</dt>
                <dd>
                    <ul id='activite_ul' class='unstyled'>
                        <!-- Type et activité principal -->
                        <li>
                            <select name='ID_TYPE' style='width: 85px' class='type_select'>
                                <?php foreach( $this->DB_type as $item ) : ?>
                                    <option value='<?php echo $item["ID_TYPE"] ?>' <?php if( $item["ID_TYPE"] == $this->etablissement['informations']["ID_TYPE"] ) echo "selected" ?> >
                                        <?php echo $item["LIBELLE_TYPE"] ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                            <select id='activite_principal_select' class='activite_select' name='ID_TYPEACTIVITE' style='width: 70%' >
                                <?php foreach( $this->DB_activite as $item ) : ?>
                                    <?php if( $item["ID_TYPE"] == $this->etablissement['informations']["ID_TYPE"] ) : ?>
                                        <option value='<?php echo $item["ID_TYPEACTIVITE"] ?>' <?php if( $item["ID_TYPEACTIVITE"] == $this->etablissement['informations']["ID_TYPEACTIVITE"] ) echo "selected" ?> >
                                            <?php echo $item["LIBELLE_ACTIVITE"] ?>
                                        </option>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </li>

                        <!-- Types et activités secondaires -->
                        <?php echo $this->partial('etablissement/partials/partial-type-activites-secondaire.phtml', array('types' => $this->DB_type, 'activites' => $this->DB_activite)) ?>
                        <?php if($this->etablissement['types_activites_secondaires']) : ?>
                        <?php foreach($this->etablissement['types_activites_secondaires'] as $type_activite_secondaire) : ?>
                            <?php echo $this->partial('etablissement/partials/partial-type-activites-secondaire.phtml', array('type_activite_secondaire' => $type_activite_secondaire, 'types' => $this->DB_type, 'activites' => $this->DB_activite)) ?>
                        <?php endforeach ?>
                        <?php endif ?>
                    </ul>
                </dd>

                <!-- R123-20 ? -->
                <dt>R123-20 ?</dt>
                <dd>
                    <p>
                        <input type='hidden' name='R12320_ETABLISSEMENTINFORMATIONS' value='0' />
                        <input type='checkbox' name='R12320_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["R12320_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> />
                    </p>
                </dd>

                <!-- Relève du droit public -->
                <dt class='champs champ_droitpublic'>R123-16 ?</dt>
                <dd class='champs champ_droitpublic'>
                    <p>
                        <input type='hidden' name='DROITPUBLIC_ETABLISSEMENTINFORMATIONS' value='0' />
                        <input type='checkbox' name='DROITPUBLIC_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["DROITPUBLIC_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> />
                    </p>
                </dd>

                <!-- Local à sommeil -->
                <dt class='champs champ_localsommeil'>Local à sommeil ?</dt>
                <dd class='champs champ_localsommeil'>
                    <p>
                        <input type='radio' name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS' value='0' <?php if( !$this->add ) echo "checked" ?> /> Non
                        <input type='radio' name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> /> Oui
                    </p>
                </dd>
            </dl>

            <!-- Rubriques -->
            <h4 class='champs_icpe champs rubrique h4_subtitle'>Rubriques ICPE <a href='#' style='font-size: 0.85em; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_rubriques').clone().appendTo( $(this).parent().next() ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); return false;">Ajouter une rubrique</a></h4>
            <table class='table table-condensed champs_icpe champs rubrique'>
                <thead>
                    <tr>
                        <th>Rubrique</th>
                        <th>Numéro</th>
                        <th>Nom</th>
                        <th>Valeur</th>
                        <th>Classement</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Rubriques -->
                    <?php echo $this->partial('etablissement/partials/partial-rubrique.phtml') ?>
                    <?php if($this->etablissement['rubriques']) : ?>
                    <?php foreach($this->etablissement['rubriques'] as $rubrique) : ?>
                        <?php echo $this->partial('etablissement/partials/partial-rubrique.phtml', array('rubrique' => $rubrique)) ?>
                    <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>

            <!-- Les effectifs -->
            <h4 class='champ_effectifs champs h4_subtitle'>Les effectifs</h4>
            <dl class='dl-horizontal champ_effectifs champs'>
                <!-- Effectif public -->
                <dt class='effectif_public'>Public</dt>
                <dd class='effectif_public'>
                    <input type='text' name='EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"] ?>' />
                </dd>

                <!-- Effectif personnel -->
                <dt>Personnel</dt>
                <dd>
                    <input type='text' name='EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"] ?>' />
                </dd>

                <!-- Effectif hebergé -->
                <dt class='effectif_heberge'>Dont hebergé</dt>
                <dd class='effectif_heberge'>
                    <input type='text' name='EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS"] ?>' />
                </dd>

                <!-- Effectif justifant le classement (que pour les 5ème catégorie) -->
                <dt class='effectif_justifiant_classement'>Justifiant le classement</dt>
                <dd class='effectif_justifiant_classement'>
                    <input type='text' name='EFFECTIFJUSTIFIANTCLASSEMENT_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFJUSTIFIANTCLASSEMENT_ETABLISSEMENTINFORMATIONS"] ?>' />
                </dd>
            </dl>

            <!-- Plan -->
            <h4 class="champ_plans champs h4_subtitle">Plans d'intervention <a href='#' style='font-size: 0.85em; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_plan').clone().appendTo( $(this).parent().next() ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); return false;">Ajouter un plan</a></h4>
            <table class='table table-condensed champ_plans champs'>
                <thead>
                    <tr>
                        <th>Type de plan</th>
                        <th>Numéro du plan</th>
                        <th>Date</th>
                        <th>A mettre à jour</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo $this->partial('etablissement/partials/partial-plan.phtml', array('types_plans' => $this->DB_typesplan)) ?>
                    <?php if($this->etablissement['plans']) : ?>
                    <?php foreach($this->etablissement['plans'] as $plan) : ?>
                        <?php echo $this->partial('etablissement/partials/partial-plan.phtml', array('plan' => $plan, 'types_plans' => $this->DB_typesplan)) ?>
                    <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>

            <!-- Etablissement lié -->
            <h4 class='h4_subtitle etablissements_lies'>Établissements liés <?php if($this->etablissement['general']) : ?> <a id='add_etablissement' href='/etablissement/add?pere=<?php echo $this->etablissement['general']['ID_ETABLISSEMENT'] ?>&libelle=<?php echo htmlspecialchars($this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES) ?>' class='edit' style='font-size: 0.85em; float: right; font-weight: normal;' >Créer un établissement enfant</a> <?php endif ?></h4>
            <dl class='dl-horizontal etablissements_lies' >
                <dt class="etablissement_pere">Père de l'établissement</dt>
                <dd class="etablissement_pere">
                    Nom de l'établissement : <strong><?php if(count($this->etablissement['parents']) > 0) echo htmlspecialchars(end($this->etablissement['parents'])["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES); elseif( isset($_GET["libelle"]) ) echo htmlspecialchars($_GET["libelle"], ENT_QUOTES)  ?></strong><br/>
                    <input placeholder="Libellé de l'établissement père ..." type='text' style='width: 100%; box-sizing: border-box; height: 2.5em' />
                    <input type='hidden' name='ID_PERE' value='<?php if(count($this->etablissement['parents']) > 0) echo end($this->etablissement['parents'])["ID_ETABLISSEMENT"]; elseif( isset($_GET["pere"]) ) echo $_GET["pere"] ?>' />
                </dd>

                <dt class="etablissements_enfants">Enfants de l'établissement</dt>
                <dd class="etablissements_enfants">
                    <table id='etablissements_enfants' class='table table-condensed'>
                        <thead>
                            <tr>
                                <th>Nom de l'établissement</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php echo $this->partial('etablissement/partials/partial-etablissement-enfant.phtml') ?>
                            <?php if($this->etablissement['etablissement_lies']) : ?>
                            <?php foreach( $this->etablissement['etablissement_lies'] as $etablissement ) : ?>
                                <?php echo $this->partial('etablissement/partials/partial-etablissement-enfant.phtml', array('etablissement' => $etablissement)) ?>
                            <?php endforeach ?>
                            <?php endif ?>
                            <tr>
                                <td>
                                    <input type='text' placeholder="Libellé d'un établissement enfant ..." id='etablissement-autocomplete' />
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </dd>
            </dl>
        </div>

        <!-- Carte de l'emplacement de l'établissement / informations  -->
        <div class='span6'>
            <h4 class="champ_adresse champs h4_subtitle">Adresse <a style='font-size: 0.85em; float: right; font-weight: normal;' data-toggle="modal" data-backdrop="false" href="#adresse-modal">Ajouter une adresse</a></h4>
			<table id='adresses' class='table table-condensed champ_adresse champs'>
                <thead>
                    <tr>
                        <th>Localisation</th>
                        <th>Type</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo $this->partial('etablissement/partials/partial-adresse.phtml') ?>
                    <?php if($this->etablissement['adresses']) : ?>
                        <?php foreach( $this->etablissement['adresses'] as $adresse ) : ?>
                            <?php echo $this->partial('etablissement/partials/partial-adresse.phtml', array('adresse' => $adresse)) ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>
			<dl class='dl-horizontal'>
				<!-- Parcelle cadastrale -->
                <dt>Parcelle cadastrale</dt>
                <dd>
					<input style='width: 220px; box-sizing: border-box; height: 30px;' type='text' id='COMPLEMENT_ETABLISSEMENTINFORMATIONS' name='COMPLEMENT_ETABLISSEMENTINFORMATIONS' placeholder='Numéro de parcelle cadastrale' value='<?php echo $this->etablissement['informations']['COMPLEMENT_ETABLISSEMENTINFORMATIONS'] ?>' />
				</dd>
			</dl>
            <h4 class='h4_subtitle'>Coordonnées</h4>
            <dl class='dl-horizontal'>
                <!-- Téléphone -->
                <dt>Téléphone</dt>
                <dd>
                    <input type='text' name='TELEPHONE_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["TELEPHONE_ETABLISSEMENT"] ?>' />
                </dd>

                <!-- Fax -->
                <dt>Exploitant</dt>
                <dd>
                    <input type='text' name='FAX_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["FAX_ETABLISSEMENT"] ?>' />
                </dd>

                <!-- Courriel -->
                <dt>Courriel</dt>
                <dd>
                    <input type='text' name='COURRIEL_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["COURRIEL_ETABLISSEMENT"] ?>' />
                </dd>
            </dl>

            <h4 class='h4_subtitle'>Données prévention</h4>
            <dl class='dl-horizontal'>
                <!-- Commission compétente -->
                <dt class="champ_commission champs">Commission</dt>
                <dd class="champ_commission champs">
                    <select name='ID_COMMISSION' class="input-xlarge" >
                        <?php foreach($this->DB_commission as $commission_type) : ?>
                            <optgroup label="<?php echo $commission_type['LIBELLE'] ?>">
                                <?php foreach($commission_type['ARRAY'] as $item ) : ?>
                                    <option value='<?php echo $item["ID_COMMISSION"] ?>' <?php if( $item["ID_COMMISSION"] == $this->etablissement['informations']["ID_COMMISSION"] ) echo "selected" ?> >
                                        <?php echo $item["LIBELLE_COMMISSION"] ?> (<?php echo $commission_type['LIBELLE'] ?>)
                                    </option>
                                <?php endforeach ?>
                            </optgroup>
                        <?php endforeach ?>
                    </select>
                </dd>

                <!-- Préventionnistes -->
                <dt>Préventionnistes</dt>
                <dd class='preventionnistes'>
                    <table id='preventionnistes' class='table table-condensed'>
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php echo $this->partial('etablissement/partials/partial-preventionniste.phtml') ?>
                            <?php if($this->etablissement['preventionnistes']) : ?>
                            <?php foreach( $this->etablissement['preventionnistes'] as $preventionniste ) : ?>
                                <?php echo $this->partial('etablissement/partials/partial-preventionniste.phtml', array('preventionniste' => $preventionniste)) ?>
                            <?php endforeach ?>
                            <?php endif ?>
                            <tr>
                                <td>
                                    <input type='text' placeholder="Ajouter un préventionniste ..." value='' />
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </dd>

                <!-- Données pratiques -->
                <dt class="champ_donnees_pratiques champs">Données pratiques</dt>
                <dd class="champ_donnees_pratiques champs">
                    <label>Nb. de préventionnistes/visite</label>
                    <input type='number'  name='NBPREV_ETABLISSEMENT' value='<?php echo $this->etablissement['donnees_pratiques']["NBPREV_ETABLISSEMENT"] ?>' />
                    <label>Durée d'une visite</label>
                    <input type='time' name='DUREEVISITE_ETABLISSEMENT' value='<?php echo $this->etablissement['donnees_pratiques']["DUREEVISITE_ETABLISSEMENT"] ?>' />
                </dd>
            </dl>
        </div>
    </div>
</form>

<!-- Style graphique des boites de dialogue -->
<style type="text/css">
	.modal-header{
		height:30px;
	}
	.modal
	{
		overflow: hidden;
		position: absolute;
		top: 0%;
		left: 40%;
	}
	.modal-dialog{
		margin-right: auto;
		margin-left: auto;
	}
	.modal-footer{
		height:30px;
	}
</style>

<!-- Boite de confirmation de l'édition (cachée par défaut) -->
<div id="confirm-modal" class="modal hide fade" >
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header" style="height: 50px">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3>Confirmation de l'édition</h3>
			</div>

			<div class="modal-body">
				<dl>
					<dt>Valeurs conseillées</dt>
					<dd>
						<ul>
							<li id='confirm-modal-commission'>Commission renseignée : <a href="#" class='label label-info confirm-modal-input'>Aucune</a>, la commission conseillée : <a href="#" class='label confirm-modal-advisable'></a></li>
							<li id='confirm-modal-periodicite'>Périodicité renseignée : <a href="#" class='label label-info confirm-modal-input'>Aucune</a>, la périodicité conseillée : <a href="#" class='label confirm-modal-advisable'></a></li>
							<li id='confirm-modal-localsommeil'>Présence de local à sommeil renseignée : <a href="#" class='label label-info confirm-modal-input'></a>, la présence conseillée : <a href="#" class='label confirm-modal-advisable'></a></li>
							<li id='confirm-modal-preventionnistes' >Préventionnistes affectés : <a href="#" class='label confirm-modal-input label-info'>Aucuns</a>, les préventionnistes conseillés : <a href="#" class='label confirm-modal-advisable'></a></li>
						</ul>
					</dd>
				</dl>
			</div>

			<div class="modal-footer" style="height: 60px">
				<a href="#" data-dismiss="modal" class="btn">Annuler</a>
				<input type='submit' value='Confirmer et sauvegarder les changements' class='btn btn-success' />
			</div>
		</div>
	</div>
</div>

<!-- Boite de construction d'adresse-->
<form style="width: 750px; top: 10px" id="adresse-modal" class="modal hide adresse fade" action='#' method='post'>
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header" style="height: 30px">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Ajouter une adresse</h3>
			</div>

			<div class="modal-body">
				<dl class='dl-horizontal'>
					<dt>Ville</dt>
					<dd>
						<input style="width: 240px" name='commune_ac' type='text' placeholder='Nom de la commune ou code postal ...' />
						<input name='code_insee' type='hidden' />
						<input name='code_postal' type='hidden' />
					</dd>

					<dt>Voie</dt>
					<dd>
						<input style="width: 240px" type='text' name='voie_ac' placeholder='Nom de la voie ...' disabled />
						<input type='hidden' name='type_voie' />
						<input type='hidden' name='voie' />
					</dd>

					<dt>Numéro</dt>
					<dd>
						<input class="input-small" type='text' name='numero' placeholder='Numéro ...' disabled />
					</dd>

					<dt>Complément d'adresse</dt>
					<dd>
						<input style="width: 240px" type='text' name='complement' placeholder="Complément d'adresse" disabled />
					</dd>

					<dt>Type de l'adresse</dt>
					<dd>
						<select  style="width: 255px">
							<option>Adresse postale</option>
						</select>
					</dd>

					<dt>Géolocalisation</dt>
					<dd>
						<?php if($this->key_ign != null) : ?><button id="geolocme" class='btn btn-small' disabled><i class="icon-map-marker"></i> Géolocaliser cette adresse (Geoportail)</button><?php endif ?>
						<?php if($this->geoconcept_url != null) : ?><button id="geolocme-geoconcept" class='btn btn-small' disabled><i class="icon-map-marker"></i> Géolocaliser cette adresse (Geoconcept)</button><?php endif ?>
						<?php /*if($key_googlemap = getenv('PREVARISC_PLUGIN_GOOGLEMAPKEY') != null) : ?><button id="geolocme_google" class='btn btn-small' disabled><i class="icon-map-marker"></i> Géolocaliser cette adresse (Googlemap)</button><?php endif */?>
						<button id="geolocme_nominatim" class='btn btn-small' disabled><i class="icon-map-marker"></i> Géolocaliser cette adresse (Nominatim)</button><br/>
						<small>Résultat : <span class='result'>Inconnu</span></small>
					</dd>

					<dt>Coordonnées</dt>
					<dd>
						 <input id="addressLongitude" name='lon' style="width: 240px" type='text' placeholder='Longitude' />
						 <input style="width: 240px" type='text' name='lat' id="addressLatitude" placeholder='Latitude' />
					</dd>
					
				</dl>
			</div>
			
			<div class="modal-body">
				<!-- Onglets -->
				<ul id='menu_nav' class="nav nav-pills" style="margin: 0; padding: 0; border-bottom: none;">
					<?php if($key_googlemap = getenv('PREVARISC_PLUGIN_GOOGLEMAPKEY')) :?>
						<li class="nav-item nav-link" ><a href="#googlemap" data-toggle="tab">Carte Google</a></li>
					<?php endif ?>
					<?php if($this->key_ign != null): ?>
						<li class="nav-item nav-link" ><a href="#geoportail" data-toggle="tab">Carte IGN</a></li>
					<?php endif ?>
					<?php if($this->geoconcept_url != null) : ?>
						<li class="nav-item nav-link" ><a href="#geoconcept" data-toggle="tab">Carte Geoconcept</a></li>
					<?php endif ?>
				</ul>
				<div id="reponse-modal" class="modal hide fade"></div>
				<div class="tab-content">
					<!-- gestion des cartes -->
				<?php if($this->key_ign != null) : ?>
					<div class="tab-pane active" id="geoportail" style="height: 350px; max-height: 350px;">
						<div id="geoportail-container" style="height: 100%; max-height: 100%;"></div>
						<!-- SDK Géoportail -->
						<script src="/js/sdk-ol/GpSDK3D.js"></script>
						<link rel="stylesheet" href="/js/sdk-ol/GpSDK3D.css"/>
						<!-- FIN SDK -->
						<!-- Déplacement du bouton FullScreen (sinon supperposé avec le gestionnaire de couches) -->
						<style>.ol-full-screen {right:9px; top:49px}</style>
						<script type="text/javascript">
						map2 = Gp.Map.load("geoportail-container", {
								configUrl : "/js/sdk-ol/autoconf-https.json",
								// chargement de la cartographie en 2D
								viewMode : "2d",
								// niveau de zoom de la carte (de 1 à 21)
								zoom : 17,
								center : {
									geolocate : true
								},
								layersOptions : {
									// COUCHE DE BASE
									"GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD" : {},
									// Autres couches à afficher rajoutées par l'utilisateur
									<?php foreach($this->couches_cartographiques as $couche_cartographique) : ?>
											<?php if ($couche_cartographique['URL_COUCHECARTO'] != null) : ?>
											<?php if ($couche_cartographique['TYPE_COUCHECARTO'] == 'WMS') : ?>
												"<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>" : {
														title : "<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>",
														format : "<?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?>",
														version : "1.3.0",
														url : "<?php echo $couche_cartographique['URL_COUCHECARTO'] ?>",
														layers : ["<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>"],
														outputFormat : "<?php echo $couche_cartographique['FORMAT_COUCHECARTO'] ?>",
														tiled : true,
														visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>,
														queryable : true,
														gfiFormat : "text/html",
														},
											<?php elseif ($couche_cartographique['TYPE_COUCHECARTO'] == 'WFS') : ?>
												"<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>" : {
														title : "<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>",
														format : "<?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?>",
														url : "<?php echo $couche_cartographique['URL_COUCHECARTO'] ?>",
														typeNames : "<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>",
														version : "2.0.0",
														//maxFeatures : 200,
														visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>,
														queryable : true,
														},
											<?php endif ?>
										<?php else : ?>
											"<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>" : {
											visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>
											},
										<?php endif ?>
									<?php endforeach ?>
									},
									// Outils additionnels à proposer sur la carte
									controlsOptions : {
										"layerSwitcher" : {},
										"search" : {
											//maximised : true
										},
										//"overview" : {},
										"orientation" : {},
										"graphicscale" : {},
										"mouseposition" : {},
										//"isocurve" : {},
										"graticule" : {},
										//"layerimport" : {},
										"length" : {},
										"area" : {},
										"azimuth" : {},
										"elevationpath" : {},
										"getfeatureinfo" : {
											layers : [
												{
													"GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD" : {},
												}
											],
											options : {
											auto : true,
											active: true,
											defaultInfoFormat: "text/html",
											defaultEvent: "singleclick",
											cursorStyle: "pointer",
											},
										},
									},
									// Repères visuels
									//markersOptions : [{
									//	content : "<b><?php echo $this->etablissement['informations']['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?></b><br/>"+
									//	"<?php echo $this->etablissement['adresses'][0]['NUMERO_ADRESSE'] ?>, <?php echo $this->etablissement['adresses'][0]['LIBELLE_RUE'] ?><br/>"+
									//	"<?php echo $this->etablissement['adresses'][0]['CODEPOSTAL_COMMUNE'] ?> <?php echo $this->etablissement['adresses'][0]['LIBELLE_COMMUNE'] ?><br/>"
									//}],
									// Appel de la fonction après le chargement de la carte
									mapEventsOptions : {
										"mapLoaded" : afterInitMap,
										//"centerChanged" : afterCenterChanged
									},
								});
								//
								function afterInitMap () {
									var fsControl = new ol.control.FullScreen({});
									map2.getLibMap().addControl(fsControl);
								};
						</script>
					</div>
				<?php endif ?>
				<?php if($key_googlemap != null) : ?>
					<div class="tab-pane" id="googlemap" style="height: 350px; max-height: 350px;">
						<div id="googlemap-container" style="height: 100%; width: 100%"></div>
						<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $key_googlemap?>"></script>
					</div>
				<?php endif ?>
				<?php if($this->geoconcept_url != null) : ?>
					<div class="tab-pane" id="geoconcept" style="height: 350px; max-height: 350px;">
						<div id='geoconcept-container'  style="height: 100%; width: 100%"></div>
						<script type="text/javascript" src="/js/geoconcept/OpenLayers.js"></script>
						<script type="text/javascript" src="/js/geoconcept/proj4js.js"></script>
						<script type="text/javascript" src="/js/geoconcept/htc-lite.js"></script>
						<?php if ($projection = getenv('PREVARISC_PLUGIN_GEOCONCEPT_PROJECTION')): ?>
							<script type="text/javascript" src="/js/geoconcept/defs/<?php echo $projection ?>.js"></script>
						<?php endif ?>
						<script type="text/javascript" src="/js/geoconcept/geoconcept.js"></script>
						<link rel="stylesheet" href="/css/geoconcept/htc.css"/>
					</div>
				<?php endif ?>
			</div>
		</div>

		<div class="modal-footer">
			<a href="#" data-dismiss="modal" class="btn btn-cancel">Annuler</a>
			<a href="#" data-dismiss="modal" class="btn btn-success" id="submit-adresse">Sauvegarder</a>
		</div>
		
		</div>
	</div>
</form>

<script type="text/javascript">
		// Variables globales
		var marker;
		// map Google
		var map;
		// map Geoportail
		var map2;
		// Init Geoportail

		function initGeoportailMap()
		{
			map2 = Gp.Map.load("geoportail-container", {
				configUrl : "/js/sdk-ol/autoconf-https.json",
				// chargement de la cartographie en 2D
				viewMode : "2d",
				// niveau de zoom de la carte (de 1 à 21)
				zoom : 17,
								center : {
									geolocate : true
								},
								layersOptions : {
									// COUCHE DE BASE
									"GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD" : {},
									// Autres couches à afficher rajoutées par l'utilisateur
									<?php foreach($this->couches_cartographiques as $couche_cartographique) : ?>
											<?php if ($couche_cartographique['URL_COUCHECARTO'] != null) : ?>
											<?php if ($couche_cartographique['TYPE_COUCHECARTO'] == 'WMS') : ?>
												"<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>" : {
														title : "<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>",
														format : "<?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?>",
														version : "1.3.0",
														url : "<?php echo $couche_cartographique['URL_COUCHECARTO'] ?>",
														layers : ["<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>"],
														outputFormat : "<?php echo $couche_cartographique['FORMAT_COUCHECARTO'] ?>",
														tiled : true,
														visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>,
														queryable : true,
														gfiFormat : "text/html",
														},
											<?php elseif ($couche_cartographique['TYPE_COUCHECARTO'] == 'WFS') : ?>
												"<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>" : {
														title : "<?php echo $couche_cartographique['NOM_COUCHECARTO'] ?>",
														format : "<?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?>",
														url : "<?php echo $couche_cartographique['URL_COUCHECARTO'] ?>",
														typeNames : "<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>",
														version : "2.0.0",
														//maxFeatures : 200,
														visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>,
														queryable : true,
														},
											<?php endif ?>
										<?php else : ?>
											"<?php echo $couche_cartographique['LAYERS_COUCHECARTO'] ?>" : {
											visibility : <?php if ($couche_cartographique['TRANSPARENT_COUCHECARTO'] == 0) : ?>false<?php else : ?>true<?php endif ?>
											},
										<?php endif ?>
									<?php endforeach ?>
									},
									// Outils additionnels à proposer sur la carte
									controlsOptions : {
										"layerSwitcher" : {},
										"search" : {
											//maximised : true
										},
										//"overview" : {},
										"orientation" : {},
										"graphicscale" : {},
										"mouseposition" : {},
										//"isocurve" : {},
										"graticule" : {},
										//"layerimport" : {},
										"length" : {},
										"area" : {},
										"azimuth" : {},
										"elevationpath" : {},
										"getfeatureinfo" : {
											layers : [
												{
													"GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD" : {},
												}
											],
											options : {
											auto : true,
											active: true,
											defaultInfoFormat: "text/html",
											defaultEvent: "singleclick",
											cursorStyle: "pointer",
											},
										},
									},
									// Repères visuels
									//markersOptions : [{
									//	content : "<b><?php echo $this->etablissement['informations']['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?></b><br/>"+
									//	"<?php echo $this->etablissement['adresses'][0]['NUMERO_ADRESSE'] ?>, <?php echo $this->etablissement['adresses'][0]['LIBELLE_RUE'] ?><br/>"+
									//	"<?php echo $this->etablissement['adresses'][0]['CODEPOSTAL_COMMUNE'] ?> <?php echo $this->etablissement['adresses'][0]['LIBELLE_COMMUNE'] ?><br/>"
									//}],
									// Appel de la fonction après le chargement de la carte
									mapEventsOptions : {
										"mapLoaded" : afterInitMap,
										//"centerChanged" : afterCenterChanged
									},
								});
								//
								function afterInitMap () {
									var fsControl = new ol.control.FullScreen({});
									map2.getLibMap().addControl(fsControl);
								};
								function afterCenterChanged () {
									//var lonlat = new ol.proj.LonLat(map2.getCenter().x, map2.getCenter().y);
									//lonlat = lonlat.transform('EPSG:3857', 'ESPG:4326');
									var lon = parseFloat(map2.getCenter().x);
									var lat = parseFloat(map2.getCenter().y);
									var coord = [parseFloat(map2.getCenter().x), parseFloat(map2.getCenter().y)];
									var lonlat = ol.coordinate.toStringXY(coord, 1);
									// wgs84-coordinates that need to be reprojected
									//var lonlat2 = ol.proj.addCoordinateTranforms(lonlat, 'E
									var lonlat2 = new ol.proj.transform(lonlat, "EPSG:3857","EPSG:4326");
									console.log(lonlat2);
									//var newlonLat = new ol.LonLat(lon, lat).transform(map2.getProjectionObject() , new ol.Projection('EPSG:4326'));
									var center = map2.getCenter();
									var newlonlat = new ol.proj.toLonLat(center, 'EPSG:4326');
									alert(newlonlat);
									$("input[name='lat']").val(map2.getCenter().x);
									$("input[name='lon']").val(map2.getCenter().y);
								};
		};
		
    $(document).ready(function() {
        // Action à la sauvegarde de l'établissement
        $("form#etablissement input[type='submit']").click(function() {
            // On va chercher les valeurs par défauts pour faire apparaitre la boite de confirmation
            var etablissements_enfants = [];
            $("table#etablissements_enfants tbody tr.etablissement_enfant").each(function(index) { etablissements_enfants[index] = $(this).find('input[name="ID_FILS_ETABLISSEMENT[]"]').first().val(); });
            $.getJSON('/api/1.0/etablissement/defaults_values', {
                genre: $("select[name='ID_GENRE']").find('option:selected').val(),
                numinsee: $("#adresses").find('tr.adresse').first().find('input[type="hidden"]').first().val(),
                type: $("select[name='ID_TYPE']").find('option:selected').val(),
                categorie: $("select[name='ID_CATEGORIE']").find('option:selected').val(),
                local_sommeil: $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS']:checked").val(),
                classe: $("select[name='ID_CLASSE']").find('option:selected').val(),
                id_etablissement_pere: $("input[name='ID_PERE']").val(),
                ids_etablissements_enfants: etablissements_enfants
            }, function(data) {
                // Si il y a des données disponibles dans les valeurs par défauts proposées, on ouvre la boite de confirmation, sinon on sauvegarde la fiche
                if(data.status == 'success' && Object.keys(data.response).length > 0) {
                    // A l'apparition de la boite de confirmation on met à jour les valeurs saisies par l'utilisateur dans la boite
                    var preventionnistes = [];
                    var date = new Date($('input[name="date"]').val());
                    var localSommeil = $('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"]:checked').val();
                    $('#confirm-modal-commission .confirm-modal-input').text($('select[name="ID_COMMISSION"] option:selected').text().replace(/ \(.*\)/gi, ""));
                    $('#confirm-modal-periodicite .confirm-modal-input').text($('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').val());
                    $('#confirm-modal-localsommeil .confirm-modal-input').text(localSommeil != undefined ? (localSommeil == 1 ? 'Oui' : 'Non') : '' );
                    $('table#preventionnistes tbody tr.preventionniste').each(function(index) { preventionnistes[index] = $(this).find('td').first().find('span').text(); });
                    $('#confirm-modal-preventionnistes .confirm-modal-input').text(preventionnistes.toString() == '' ? 'Aucuns' : preventionnistes.toString());
                    // On met à jour les valeurs par défauts
                    $('#confirm-modal-commission .confirm-modal-advisable').attr('id', data.response.commission ? data.response.commission.ID_COMMISSION : '').text(data.response.commission ? data.response.commission.LIBELLE_COMMISSION : '');
                    $('#confirm-modal-periodicite .confirm-modal-advisable').text(data.response.periodicite);
                    $('#confirm-modal-localsommeil .confirm-modal-advisable').text(data.response.local_sommeil !== undefined ? (data.response.local_sommeil == true ? 'Oui' : 'Non') : '');
                    if(data.response.preventionnistes && data.response.preventionnistes.length > 0) {
                        var preventionnistes = [];
                        var preventionnistes_ids = [];
                        for(var x in data.response.preventionnistes) {
                            preventionnistes[x] = data.response.preventionnistes[x].nom + ' ' + data.response.preventionnistes[x].prenom;
                            preventionnistes_ids[x] = data.response.preventionnistes[x].uid;
                        }
                        $('#confirm-modal-preventionnistes .confirm-modal-advisable').attr('ids', preventionnistes_ids.toString()).text(preventionnistes.toString());
                    }
                    $('#confirm-modal').find('li').removeClass('confirm-modal-hide');
                    $('#confirm-modal').find('li').each(function(index) {
                        if($(this).find('.confirm-modal-input').text().trim() == $(this).find('.confirm-modal-advisable').text().trim() || $(this).find('.confirm-modal-advisable').text().trim() == '') {
                            $(this).addClass("confirm-modal-hide");
                        }
                    });
                    if($('#confirm-modal').find('li.confirm-modal-hide').length == 4) {
                        $("form#etablissement").submit();
                    }
                    else {
                        $('#confirm-modal').modal({show: true});
                    }
                }
                else {
                    $("form#etablissement").submit();
                }
            });
            return false;
        });

        // Comportement des labels interactifs dans la boite de confirmation
        $('#confirm-modal a.label').click(function() {
            $(this).parent().find('a.label').toggleClass('label-info');
        });

        // Gestion de la prise en compte des valeurs par défaut dans la boite de confirmation
        $('#confirm-modal input[type="submit"]').click(function() {
            $('#confirm-modal').find('a.label-info').each(function(index) {
                if($(this).hasClass('confirm-modal-advisable')) {
                    switch($(this).parent().attr('id')) {
                        case 'confirm-modal-preventionnistes':
                            $('table#preventionnistes').remove();
                            var preventionnistes_ids = $(this).attr('ids').split(",");
                            for(var x in preventionnistes_ids) {
                                $('<input>').attr({type: 'hidden', name: 'ID_UTILISATEUR[]', value: preventionnistes_ids[x]}).appendTo('form#etablissement');
                            }
                            break;
                        case 'confirm-modal-commission':
                            $('select[name="ID_COMMISSION"]').find('option[value=' + $(this).attr('id') + ']').attr('selected', true);
                            break;
                        case 'confirm-modal-periodicite':
                            $('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').val($(this).text());
                            break;
                        case 'confirm-modal-localsommeil':
                            $('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"][value=1]').attr('checked', $(this).text() == 'Oui');
                            break;
                    }
                }
            });

            $("form#etablissement").submit();
        });

        // Ajout d'une adresse
        $("form.adresse a#submit-adresse").live('click', function() {
            time = Date.now();
            node = $('#prototype_adresse').clone().prependTo( $('table.champ_adresse') ).removeClass('hide prototypes').addClass('adresse').attr('id', '');
            node.find('input[name="ADRESSES[-1][LON_ETABLISSEMENTADRESSE]"]').val($('form.adresse').find('input[name="lon"]').val());
            node.find('input[name="ADRESSES[-1][LAT_ETABLISSEMENTADRESSE]"]').val($('form.adresse').find('input[name="lat"]').val());
            node.find('input[name="ADRESSES[-1][NUMERO_ADRESSE]"]').val($('form.adresse').find('input[name="numero"]').val());
            node.find('input[name="ADRESSES[-1][ID_RUE]"]').val($('form.adresse').find('input[name="voie"]').val());
            node.find('input[name="ADRESSES[-1][NUMINSEE_COMMUNE]"]').val($('form.adresse').find('input[name="code_insee"]').val());
            node.find('input[name="ADRESSES[-1][COMPLEMENT_ADRESSE]"]').val($('form.adresse').find('input[name="complement"]').val());
            node.find('span').text($('form.adresse').find('input[name="numero"]').val() + " " + $('form.adresse').find('input[name="voie_ac"]').val() + " " + $('form.adresse').find('input[name="code_postal"]').val() + " " + $('form.adresse').find('input[name="commune_ac"]').val());
            node.find('input').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); });
            $('form.adresse').find('button.close').click();
            return false;
        });

        // Gestion des boites modales
        $("a[data-toggle='modal']").click(function() {
            var target = $(this).attr("data-target");
            var url = $(this).attr("href");
            $(target).load(url);
        });

        // Action sur le changement du genre (affichage des champs)
        $("select[name='ID_GENRE']").change(function() {
            $('.champs').hide();
            $('.etablissement_pere, .etablissements_enfants, .etablissements_lies').show();
            switch($(this).find('option:selected').val()) {
                // Site
                case '1':
                    $('.etablissement_pere').hide();
                    break;

                // Établissement
                case '2':
                    $('.champ_categorie, .champ_periodicite, .champ_types, .champ_effectifs, .champ_plans, .champ_adresse, .champ_commission, .champ_localsommeil, .champ_donnees_pratiques, .champ_droitpublic').show();
                    break;

                // Cellule
                case '3':
                    $('.champ_types, .champ_effectifs, .champ_plans, .champ_donnees_pratiques').show();
                    $('.etablissements_enfants').hide();
                    break;

                // Habitation
                case '4':
                    $('.champ_famille, .champ_adresse').show();
                    $('.etablissements_enfants').hide();
                    break;

                // IGH
                case '5':
                    $('.champ_periodicite, .champ_classe, .champ_effectifs, .champ_plans, .champ_adresse, .champ_commission, .champ_donnees_pratiques').show();
                    $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").attr('checked', false).change();
                    break;

                // EIC
                case '6':
                    $('.champ_icpe, .champ_effectifs, .champ_plans, .champ_adresse').show();
                    $('.etablissements_enfants, .effectif_heberge, .effectif_public').hide();
                    $("input[name='ICPE_ETABLISSEMENTINFORMATIONS']").change();
                    $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").attr('checked', false).change();
                    break;

                // Camping
                case '7':
                    $('.champ_effectifs, .effectif_public, .champ_adresse, .champ_plans').show();
                    $('.etablissements_enfants').hide();
                    break;

                // Manifestation Temporaire
                case '8':
                    $('.champ_effectifs, .effectif_public, .champ_adresse, .champ_plans').show();
                    $('.etablissements_enfants').hide();
                    break;

                // IOP
                case '9':
                    $('.champ_effectifs, .effectif_public, .champ_adresse, .champ_plans').show();
                    $('.etablissements_enfants').hide();
                    break;

                // Zone
                case '10':
                    $('.champ_classement, .champ_adresse').show();
                    $('.etablissements_lies').hide();
                    break;
            }
        }).change();

        // Actions sur le changement de type principal
        changementLibelleEffectifPublic = function(self) {
            // Si l'établissement est un parking, alors l'effectif public est le nombre de places de stationnement
            if($(self).val() == 16) {
                $("dt.effectif_public").html('Places de stationnement');
            }
            else {
                $("dt.effectif_public").html('Public');
            }
        };

        $("select[name='ID_TYPE']").change(function(){
            changementLibelleEffectifPublic(this);
        }).change();

        // Actions sur le changement de catégorie
        $("select[name='ID_CATEGORIE']").change(function() {
            // Gestion de l'affichage de l'effectif justifiant le classement (uniquement pour les 5ème catégorie)
            if($(this).val() == 5) {
                $(".effectif_justifiant_classement").show();
            } else {
                $(".effectif_justifiant_classement").hide().find("input").val("");
            }
        }).change();

        // Actions sur le statut ICPE
        $("input[name='ICPE_ETABLISSEMENTINFORMATIONS']").change(function() {
            if( $(this).is(":checked") && $("select[name='ID_GENRE'] option:selected").val() == 6 ) {
                $(".rubrique").show();
            } else {
                $(".rubrique").hide();
            }
        }).change();

        // Affichage ou non de l'effectif hebergé en fonction de la checkbox local sommeil
        $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS']").change(function() {
            if( $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").is(":checked") )
                $(".effectif_heberge").show();
            else
                $(".effectif_heberge").hide();
        }).change();

        // Fonction pour afficher les activités du type
        $("select.type_select").live("change", function() {
            activites = <?php echo Zend_Json::encode($this->DB_activite) ?>;
            $(this).next().find("option").remove();
            for( var x in activites) {
                if( activites[x]["ID_TYPE"] == $(this).val() ) {
                    $(this).next().append($("<option />").val(activites[x]["ID_TYPEACTIVITE"]).text(activites[x]["LIBELLE_ACTIVITE"]));
                }
            }
        });

        // On choisit d'initialiser ou de remettre à 0 les activités en fonction du type
        $("select.type_select").each(function(index) {
            if($(this).next().find("option").length == 0) {
                $(this).change();
            }
        });

        // Auto-complétion de l'établissement père
        $(".etablissement_pere input[type='text']").typeahead({
            minLength: 3,
            source: function(query, process) {
                return $.ajax({
                    url: "/api/1.0/search/etablissements",
                    type: 'get',
                    data: {
                        label: query
                    },
                    success: function (result) {
                        etablissements = [];
                        $.each(result.response.results, function (i, etablissement) {
                            switch(etablissement.ID_GENRE)
                            {
                                case 1:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_SITE;
                                    break;

                                case 3:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_CELLULE;
                                    break;

                                default:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_DEFAULT == null ? "non localisé" : etablissement.LIBELLE_COMMUNE_ADRESSE_DEFAULT;
                            }

                            etablissements.push("<span class='muted'>[" + etablissement.LIBELLE_GENRE + "]</span> <span data-id='" + etablissement.ID_ETABLISSEMENT + "' class='result'>" + etablissement.LIBELLE_ETABLISSEMENTINFORMATIONS + "</span> - <small>" + LIBELLE_COMMUNE + "</small>");
                        });

                        process(etablissements);
                    }
                });
            },
            highlighter: function (item) {
                libelle = $($.parseHTML(item)).last().prev().text();
                libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
                html = $.parseHTML(item);
                $(html).last().prev().text(libelle);
                html = $(html).text();
                return item.replace( item, html );
            },
            updater: function (item) {
                $(".etablissement_pere strong").text($($.parseHTML(item)).last().prev().text());
                $(".etablissement_pere input[type='hidden']").val($($.parseHTML(item)).last().prev().data('id'));
                return;
            }
        });

        // Auto-complétion des établissements enfants
        $(".etablissements_enfants input[type='text']").typeahead({
            minLength: 3,
            source: function(query, process) {
                return $.ajax({
                    url: "/api/1.0/search/etablissements",
                    type: 'get',
                    data: {
                        label: query
                    },
                    success: function (result) {
                        etablissements = [];
                        $.each(result.response.results, function (i, etablissement) {
                            switch(etablissement.ID_GENRE)
                            {
                                case 1:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_SITE;
                                    break;

                                case 3:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_CELLULE;
                                    break;

                                default:
                                    LIBELLE_COMMUNE = etablissement.LIBELLE_COMMUNE_ADRESSE_DEFAULT == null ? "non localisé" : etablissement.LIBELLE_COMMUNE_ADRESSE_DEFAULT;
                            }

                            etablissements.push("<span class='muted'>[" + etablissement.LIBELLE_GENRE + "]</span> <span data-id='" + etablissement.ID_ETABLISSEMENT + "' class='result'>" + etablissement.LIBELLE_ETABLISSEMENTINFORMATIONS + "</span> - <small>" + LIBELLE_COMMUNE + "</small>");
                        });

                        process(etablissements);
                    }
                });
            },
            highlighter: function (item) {
                libelle = $($.parseHTML(item)).last().prev().text();
                libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
                html = $.parseHTML(item);
                $(html).last().prev().text(libelle);
                html = $(html).text();
                return item.replace( item, html );
            },
            updater: function (item) {
                node = $('#prototype_etablissements_enfants').clone().prependTo( $('.etablissements_enfants table') ).removeClass('hide  prototypes').addClass('etablissement_enfant').attr('id', '');
                node.find('span').text($($.parseHTML(item)).last().prev().text());
                node.find("input[type='hidden']").val($($.parseHTML(item)).last().prev().data('id'));
                return;
            }
        });

        // Auto-complétion des préventionnistes => 22
        $(".preventionnistes input[type='text']").typeahead({
            minLength: 3,
            source: function(query, process) {
                return $.ajax({
                    url: "/api/1.0/search/users",
                    type: 'post',
                    data: {
                        name: query,
                        fonctions: 22,
                        limit: 100,
                    },
                    success: function (result) {
                        preventionnistes = [];
                        $.each(result.response.results, function (i, preventionniste) {
                            preventionnistes.push("<span data-id='" + preventionniste.uid + "'>" + preventionniste.NOM_UTILISATEURINFORMATIONS + " " + preventionniste.PRENOM_UTILISATEURINFORMATIONS + "</span>");
                        });

                        process(preventionnistes);
                    }
                });
            },
            highlighter: function (item) {
                libelle = $($.parseHTML(item)).last().text();
                libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
                html = $.parseHTML(item);
                $(html).last().text(libelle);
                html = $(html).text();
                return item.replace( item, html );
            },
            updater: function (item) {
                node = $('#prototype_preventionniste').clone().prependTo( $('.preventionnistes table') ).removeClass('hide prototypes').addClass('preventionniste').attr('id', '');
                node.find('span').text($($.parseHTML(item)).last().text());
                node.find("input[type='hidden']").val($($.parseHTML(item)).last().data('id'));
                return;
            }
        });

        // Auto complétion de la ville
        $("input[name='commune_ac']").autocomplete("/api/1.0/adresse/get_communes", {
            minChars: 2,
            parse: function(data) {
                return $.map(data["response"], function(row) {return {data: row,value: row.LIBELLE_COMMUNE,result: row.LIBELLE_COMMUNE}});
            },
            formatItem: function(item) {
                return item.LIBELLE_COMMUNE + " (" + item.NUMINSEE_COMMUNE + ")";
            }
        }).result(function(e, item) {
            $("#adresse-modal input[name='code_insee']").val( item.NUMINSEE_COMMUNE );
            $("#adresse-modal input[name='code_postal']").val( item.CODEPOSTAL_COMMUNE );
            $("#adresse-modal input[name='voie_ac']").removeAttr('disabled');
        }).click(function() {
            $(this).val("");
            $("#adresse-modal input[name='voie_ac'], #adresse-modal input[name='numero'], #adresse-modal input[name='complement']").val("").attr("disabled", true).blur();
            $("#adresse-modal input[name='voie']").val("").blur();
        });

        // Auto complétion de la rue
        $("input[name='voie_ac']").autocomplete('/api/1.0/adresse/get_voies', {
            minChars: 3,
            extraParams: { code_insee: function(){ return $("#adresse-modal input[name='code_insee']").val() } },
            parse: function(data) {
                return $.map(data["response"], function(row) { return {data: row,value: row.LIBELLE_RUE,result: row.LIBELLE_RUE} });
            },
            formatItem: function(item) {
                return item.LIBELLE_RUE + ' (code insee : ' + item.NUMINSEE_COMMUNE + ')';
            }
        }).result(function(e, item) {
            $("#adresse-modal input[name='voie']").val( item.ID_RUE );
            $("#adresse-modal input[name='type_voie']").val( item.ID_RUETYPE );
            $("#adresse-modal input[name='numero'], #adresse-modal input[name='complement']").removeAttr("disabled");
			$("#adresse-modal button[id='geolocme']").removeAttr("disabled");
			$("#adresse-modal button[id='geolocme_nominatim']").removeAttr("disabled");
			$("#adresse-modal button[id='geolocme_geoportail']").removeAttr("disabled");
        }).click(function() {
            $(this).val("");
            $("#adresse-modal input[name='numero'], #adresse-modal input[name='complement']").val("").attr("disabled", true).blur();
        });
		
		//<!-- Autoriser le déplacement de la fenêtre par le header -->
		$("#adresse-modal").draggable({handle: ".modal-header"});
		$("#confirm-modal").draggable({handle: ".modal-header"});

		// PARTIE GEOLOCALISATION CARTOGRAPHIE
		//Initialisation des cartes en fonction des clés
		<?php if($this->key_ign != null) : ?>
			//initGeoportailMap()
		<?php endif ?>
		<?php if($key_googlemap != null) :?>
			initGoogleMap()
		<?php endif ?>

		// Init Googlemap
		function initGoogleMap()
		{
			var lat = 48.852969;
			var lon = 4.59590009;
			map = new google.maps.Map(document.getElementById("googlemap-container"), {
				//Nous plaçons le centre de la carte avec les coordonnées ci-dessus
				center: new google.maps.LatLng(lat, lon), 
				// Nous définissons le zoom par défaut
				zoom: 11,
				// zoom sur double click désactv
				disableDoubleClickZoom: true,
				// Nous définissons le type de carte (ici carte routière)
				mapTypeId: google.maps.MapTypeId.ROADMAP, 
				// Nous activons les options de contrôle de la carte (plan, satellite...)
				mapTypeControl: true,
				scrollwheel: true, 
				mapTypeControlOptions: {
					// Cette option sert à définir comment les options se placent
					style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR 
				},
				// Activation des options de navigation dans la carte (zoom...)
				navigationControl: true, 
				navigationControlOptions: {
					// Comment ces options doivent-elles s'afficher
					style: google.maps.NavigationControlStyle.ZOOM_PAN 
				}
			});
		};

		// Géolocalisation de l'adresse avec Géoportail
        $('#adresse-modal #geolocme').click(function(e) {
			e.preventDefault();
			var adresse = "";
			var numero = $("input[name='numero']").val().trim();
			var voie = $("input[name='voie_ac']").val().trim();
			var codepostal = $("input[name='code_postal']").val();
			var commune = $("input[name='commune_ac']").val().replace(/\(.*\)/g, '');
			if (!commune) {
				$("span.result").text("Pas de commune renseignée");
				return false;
			}
			if (!voie) {
				$("span.result").text("Pas de voie renseignée");
				return false;
			}
			if (numero) {
				adresse += numero + ", ";
			}
			adresse += voie + ", " + codepostal +  ", " + commune;
			$("span.result").text("Géolocalisation en cours...");
			<?php if($key_googlemap != null) :?>
				// Récupération de l'adresse tapée dans le formulaire
				var geocoder = new google.maps.Geocoder();
				geocoder.geocode( { 'address': adresse}, function(results, status) {
					if (status == google.maps.GeocoderStatus.OK)
					{
						$("span.result").text("OK");
						map.setCenter(results[0].geometry.location);
						// Récupération des coordonnées GPS du lieu tapé dans le formulaire
						var strposition = results[0].geometry.location+"";
						strposition=strposition.replace('(', '');
						strposition=strposition.replace(')', '');
						// Affichage des coordonnées
						var lonlat=strposition.split(",");
						$("input[name='lat']").val(lonlat[0]);
						$("input[name='lon']").val(lonlat[1]);
						// Création du marqueur du lieu (épingle)
						marker = new google.maps.Marker({
							map: map,
							position: results[0].geometry.location,
							title: "GEOLOCALISATION DE L'ETABLISSEMENT",
							//zoom:18,
							draggable:true
						});
						// Info-bulle avec l'adresse recherchée
						var infowindow = new google.maps.InfoWindow({
							content:
							"<b>Position de l'établissement</b> <br />"+
							$("input[name='numero']").val() + " " + $("input[name='voie_ac']").val() + "<br/>" +
							$("input[name='code_postal']").val() + " " + $("input[name='commune_ac']").val()
						});
						infowindow.open(map,marker);
						//map.setCenter(new google.maps.LatLng(geolocations[0].lat,geolocations[0].lon));
						map.setZoom(18);
						// Si l'on déplace le marker, les coordonnées sont mises à jour
						marker.addListener('drag', handleEvent);
						function handleEvent(event) {
							$("input[name='lat']").val(event.latLng.lat());
							$("input[name='lon']").val(event.latLng.lng());
						};
						google.maps.event.addListener(marker, 'rightclick', function(events) {
						   if(confirm("Etes-vous sur de vouloir supprimer ce marqueur ?")){
							  this.setMap(null);
						   }
						});
					}
					else
					{
						$("span.result").text("Adresse introuvable: " + status);
					}
				});
			<?php endif ?>
			<?php if($this->key_ign != null) : ?>
				//var lonlat = new OpenLayers.LonLat(geolocations[0].lon, geolocations[0].lat);
				//lonlat = lonlat.transform('EPSG:4326', viewer.getProjection());
				//putMarkerAt(viewer, lonlat, viewer.getProjection());
				//map2.setCenter(parseFloat(geolocations[0].lon), parseFloat(geolocations[0].lat));
				// Récupération de l'adresse tapée dans le formulaire
				var geocoder = new google.maps.Geocoder();
				geocoder.geocode( { 'address': adresse}, function(results, status) {
					if (status == google.maps.GeocoderStatus.OK)
					{
						$("span.result").text("OK");
						//map.setCenter(results[0].geometry.location);
						// Récupération des coordonnées GPS du lieu tapé dans le formulaire
						var strposition = results[0].geometry.location+"";
						strposition=strposition.replace('(', '');
						strposition=strposition.replace(')', '');
						// Affichage des coordonnées
						var lonlat=strposition.split(",");
						$("input[name='lat']").val(lonlat[0]);
						$("input[name='lon']").val(lonlat[1]);
						var lon = parseFloat(lonlat[1]);
						var lat = parseFloat(lonlat[0]);
						map2.setCenter({
							x:lon,
							y:lat,
							projection : "EPSG:4326"
						});
						map2.setZoom(17);
					}
					else
					{
						$("span.result").text("Adresse introuvable: " + status);
					}
				});
			<?php endif ?>
			<?php if ($this->geoconcept_url != null): ?>
				var lonlat = new OpenLayers.LonLat(geolocations[0].lon, geolocations[0].lat);
				lonlat = lonlat.transform(new OpenLayers.Projection('EPSG:4326'), new OpenLayers.Projection(map.getProjection()));
				map.moveTo(lonlat, 8);
				geoConceptPutMarkerAt(map, lonlat);
				map.updateSize();
			<?php endif ?>
		});
		
		// Géolocalisation de l'adresse avec Nominatim
        $('#adresse-modal #geolocme_nominatim').click(function() {
			element = $(this);
            $.ajax({
                url: "//nominatim.openstreetmap.org/search",
                dataType: 'json',
                timeout: 10000,
                data: {
                    format: "json",
                    limit: 1,
                    countrycodes: "FR",
                    street: $("input[name='numero']").val() + " " + $("input[name='voie_ac']").val(),
                    city: $("input[name='commune_ac']").val(),
                    postalcode: $("input[name='code_postal']").val()
                },
                beforeSend: function() {
                    $("span.result").text("Géolocalisation en cours ...");
                },
                success: function(geolocations) {
                    $("span.result").text("OK");
                    if(geolocations.length > 0) {
                        $("span.result").text("OK");
                        $("input[name='lon']").val(geolocations[0].lon);
                        $("input[name='lat']").val(geolocations[0].lat);
						// Traitement en fonction des cartes disponibles
						<?php if($key_googlemap != null) :?>
							marker = new google.maps.Marker({
                                position: new google.maps.LatLng(geolocations[0].lat, geolocations[0].lon),
                                map: map,
                                title: "GEOLOCALISATION DE L'ETABLISSEMENT",
								draggable:true
							});
							// Info-bulle avec l'adresse recherchée
							var infowindow = new google.maps.InfoWindow({
                                content:
                                "<b>Position de l'établissement</b> <br />"+
                                $("input[name='numero']").val() + " " + $("input[name='voie_ac']").val() + "<br/>" +
                                $("input[name='code_postal']").val() + " " + $("input[name='commune_ac']").val()
							});
							infowindow.open(map,marker);
							map.setCenter(new google.maps.LatLng(geolocations[0].lat,geolocations[0].lon));
							map.setZoom(18);
							// Si l'on déplace le marker, les coordonnées sont mises à jour
							marker.addListener('drag', handleEvent);
							function handleEvent(event) {
								$("input[name='lat']").val(event.latLng.lat());
								$("input[name='lon']").val(event.latLng.lng());
							};
							google.maps.event.addListener(marker, 'rightclick', function(events) {
								if(confirm("Etes-vous sur de vouloir supprimer ce marqueur ?")){
									this.setMap(null);
								}
							});
						<?php endif ?>
						
                        <?php if($this->key_ign != null) : ?>
						
                            //var viewer = map2.getViewer().getMap(); 
							//var lonlat = new OpenLayers.LonLat(geolocations[0].lon, geolocations[0].lat);
                            //lonlat = lonlat.transform('EPSG:4326', viewer.getProjection());
                            //putMarkerAt(map2, lonlat, map.getProjection());
                            //viewer.setCenter(parseFloat(geolocations[0].lon), parseFloat(geolocations[0].lat));
                            var lon = parseFloat(geolocations[0].lon);
							var lat = parseFloat(geolocations[0].lat);
							map2.setCenter({
								x:lon,
								y:lat,
								projection : "EPSG:4326"
							});
							map2.setZoom(18);
							map2.listen(centerChanged, updateLonLat, this);
							function updateLonLat()
							{
								alert("ça bouge");
								//$("input[name='lat']").val(Gp.Center.x);
							};
							map2.on('pointermove', function(e) {
								if (e.dragging) {
								  $(element).popover('destroy');
								  return;
								}
							});
						<?php endif ?>
						
                        <?php if ($this->geoconcept_url != null): ?>
                            var lonlat = new OpenLayers.LonLat(geolocations[0].lon, geolocations[0].lat);
                            lonlat = lonlat.transform(new OpenLayers.Projection('EPSG:4326'), new OpenLayers.Projection(map.getProjection()));
                            map.moveTo(lonlat, 8);
                            geoConceptPutMarkerAt(map, lonlat);
                            map.updateSize();
                        <?php endif ?>
                    }
                    else {
                        $("span.result").text("Introuvable");
                        $("input[name='lon']").val(0);
                        $("input[name='lat']").val(0);
                    }
                },
                error: function() {
                    $("span.result").text("Serveur de géolocalisation introuvable");
                }
            });
            return false;
        });
	});

	$(document).ready(function() {
        // Par défaut, on montre le premier onglet disponible (carte, diapo, ou plans) sinon rien
        $('#menu_nav a:first').tab('show');
    });
</script>