<?php echo $this->render('etablissement/partials/header.phtml') ?>

<form method='post'>

    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn btn-default' href="<?php echo $this->url(array('id' => $this->etablissement['general']['ID_ETABLISSEMENT']), 'ets_descriptifs', true) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h2>Modification des descriptifs</h2>

    <h3>Historique de l'établissement</h3>
    <textarea name='historique' cols='' rows='' style='width: 100%; height: 150px;' class='form-control' ><?php echo $this->historique ?></textarea>

    <h3>Descriptif</h3>
    <textarea name='descriptif' cols='' rows='' style='width: 100%; height: 150px;' class='form-control' ><?php echo $this->descriptif ?></textarea>

    <h3>Dérogations accordées</h3>
    <textarea name='derogations' cols='' rows='' style='width: 100%; height: 150px;' class='form-control' ><?php echo $this->derogations ?></textarea>

    <h3>Descriptif technique</h3>
    <?php
        foreach($this->champs_descriptif_technique as $title => $champ_destech) {
            echo "<h4 class='lead'>".$title."</h4>";
            echo "<dl>";
            foreach($champ_destech as $key => $value) {
                echo "<dt>".$key."</dt>";
                echo "<dd>";

                switch($value['type']) {
                    case 'tinyint':
                        echo "<input type='hidden' name='descriptifs_techniques[" . $value['key'] . "]' value='0' />";
                        echo "<input type='checkbox' name='descriptifs_techniques[" . $value['key'] . "]' " . ($value['value'] == 1 ? 'checked' : '') . " value='1' />";
                        break;

                    case 'int':
                        echo "<input class='form-control' type='number' name='descriptifs_techniques[" . $value['key'] . "]' value='" . ($value['value'] == '' ? '0' : $value['value']) . "' />";
                        break;

                    case 'text':
                        echo "<textarea class='form-control' name='descriptifs_techniques[" . $value['key'] . "]' cols='' rows='' style='width: 100%; height: 50px;' >" . $value['value'] . "</textarea>";
                        break;

                    default:
                        echo "<input class='form-control' type='text' name='descriptifs_techniques[" . $value['key'] . "]' value='" . $value['value'] . "' />";
                }

                echo "</dd>";
            }
            echo "</dl>";
        }
    ?>

</form>
