<?php echo $this->render('etablissement/partials/header.phtml') ?>

<form id='etablissement' class='form-horizontal' method='post' >

    <?php if($this->add) : ?>
    <div class='pull-right' >
        <input type='submit' class="btn btn-success" value="Ajouter l'établissement">
        <input type="hidden" name="date" value='<?php echo date("Y-m-d H:i:s") ?>'>
    </div>
    <h1 class='page-header'>Ajout d'un établissement</h1>
    <?php else : ?>
    <div class='pull-right' >
        <a class='btn btn-default' href="<?php echo $this->url(array("id" => $this->etablissement['general']['ID_ETABLISSEMENT']), 'ets', true) ?>">Annuler la modification</a>
        <input type='submit' class="btn btn-success" value='Sauvegarder'>
    </div>
    <h2>Modification de l'établissement</h2>
    <?php endif ?>

    <div class='row'>

        <!-- Informations générales de l'établissement -->
        <div class='col-xs-6'>

            <h3>Général</h3>
            <div>
              <div class="form-group">
                <div class="col-sm-12">
                  <input class='form-control input-lg' type='text' placeholder="Libellé de l'établissement" name='LIBELLE_ETABLISSEMENTINFORMATIONS' value='<?php if ( $this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"] ) echo htmlspecialchars($this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES) ?>' />
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label">Identifiant</label>
                <div class="col-sm-9">
                  <input class='form-control' type='text' name='NUMEROID_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["NUMEROID_ETABLISSEMENT"]?>' />
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label">Statut</label>
                <div class="col-sm-9">
                  <select class='form-control' name='ID_STATUT'>
                      <?php foreach( $this->DB_statut as $item ) : ?>
                          <option value='<?php echo $item["ID_STATUT"] ?>' <?php if( $item["ID_STATUT"] == $this->etablissement['informations']["ID_STATUT"] ) echo "selected" ?> >
                              <?php echo $item["LIBELLE_STATUT"] ?>
                          </option>
                      <?php endforeach ?>
                  </select>
                </div>
              </div>
            </div>

            <h3>Classement</h3>
            <div>
              <div class="form-group">
                <label class="col-sm-3 control-label">Genre</label>
                <div class="col-sm-9">
                  <select class='form-control' name='ID_GENRE'>
                      <?php foreach( $this->DB_genre as $genre ) : ?>
                          <option value='<?php echo $genre["ID_GENRE"] ?>' <?php if( $genre["ID_GENRE"] == $this->etablissement['informations']["ID_GENRE"] ) echo "selected" ?> >
                              <?php echo $genre["LIBELLE_GENRE"] ?>
                          </option>
                      <?php endforeach ?>
                  </select>
                </div>
              </div>

              <div class="form-group champ_icpe champs">
                <label class="col-sm-3 control-label">ICPE</label>
                <div class="col-sm-9">
                  <input type='hidden' name='ICPE_ETABLISSEMENTINFORMATIONS' value='0' />
                  <input type='checkbox' name='ICPE_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["ICPE_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> />
                </div>
              </div>

              <div class="form-group champ_categorie champs">
                <label class="col-sm-3 control-label">Catégorie</label>
                <div class="col-sm-9">
                  <select class='form-control' name='ID_CATEGORIE'>
                      <?php foreach( $this->DB_categorie as $item ) : ?>
                          <option value='<?php echo $item["ID_CATEGORIE"] ?>' <?php if( $item["ID_CATEGORIE"] == $this->etablissement['informations']["ID_CATEGORIE"] ) echo "selected" ?> >
                              <?php echo $item["LIBELLE_CATEGORIE"] ?>
                          </option>
                      <?php endforeach ?>
                  </select>
                </div>
              </div>

              <div class="form-group champ_famille champs">
                <label class="col-sm-3 control-label">Famille</label>
                <div class="col-sm-9">
                  <select class='form-control' name='ID_FAMILLE'>
                      <?php foreach( $this->DB_famille as $item ) : ?>
                          <option value='<?php echo $item["ID_FAMILLE"] ?>' <?php if( $item["ID_FAMILLE"] == $this->etablissement['informations']["ID_FAMILLE"] ) echo "selected" ?> >
                              <?php echo $item["LIBELLE_FAMILLE"] ?>
                          </option>
                      <?php endforeach ?>
                  </select>
                </div>
              </div>

              <div class="form-group champ_classe champs">
                <label class="col-sm-3 control-label">Classe</label>
                <div class="col-sm-9">
                  <select class='form-control' name='ID_CLASSE'>
                      <?php foreach( $this->DB_classe as $item ) : ?>
                          <option value='<?php echo $item["ID_CLASSE"] ?>' <?php if( $item["ID_CLASSE"] == $this->etablissement['informations']["ID_CLASSE"] ) echo "selected" ?> >
                              <?php echo $item["LIBELLE_CLASSE"] ?>
                          </option>
                      <?php endforeach ?>
                  </select>
                </div>
              </div>

              <div class="form-group champ_periodicite champs">
                <label class="col-sm-3 control-label">Périodicité (en mois)</label>
                <div class="col-sm-9">
                  <input type='number' class='form-control' name='PERIODICITE_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["PERIODICITE_ETABLISSEMENTINFORMATIONS"] ?>' />
                </div>
              </div>
            </div>

            <h3 class='champ_types champs'>Activités <a href='#' style='font-size: 14px; line-height: 24px; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_types_activites_secondaires').clone().appendTo( $('#activite_ul') ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); $('#activite_ul li:last select').change(); return false;">Ajouter un type et une activité secondaire</a></h3>
            <div class='champ_types champs'>
              <div class="form-group">
                <label class="col-sm-3 control-label">Types et activités</label>
                <div class="col-sm-9">
                  <ul id='activite_ul' class='list-unstyled'>
                      <!-- Type et activité principal -->
                      <li>
                          <select name='ID_TYPE' class='type_select form-control' style='display: inline; width: 20%;'>
                              <?php foreach( $this->DB_type as $item ) : ?>
                                  <option value='<?php echo $item["ID_TYPE"] ?>' <?php if( $item["ID_TYPE"] == $this->etablissement['informations']["ID_TYPE"] ) echo "selected" ?> >
                                      <?php echo $item["LIBELLE_TYPE"] ?>
                                  </option>
                              <?php endforeach ?>
                          </select>
                          <select id='activite_principal_select' class='activite_select form-control' name='ID_TYPEACTIVITE' style='display: inline; width: 79%;' >
                              <?php foreach( $this->DB_activite as $item ) : ?>
                                  <?php if( $item["ID_TYPE"] == $this->etablissement['informations']["ID_TYPE"] ) : ?>
                                      <option value='<?php echo $item["ID_TYPEACTIVITE"] ?>' <?php if( $item["ID_TYPEACTIVITE"] == $this->etablissement['informations']["ID_TYPEACTIVITE"] ) echo "selected" ?> >
                                          <?php echo $item["LIBELLE_ACTIVITE"] ?>
                                      </option>
                                  <?php endif ?>
                              <?php endforeach ?>
                          </select>
                      </li>

                      <!-- Types et activités secondaires -->
                      <?php echo $this->partial('etablissement/partials/partial-type-activites-secondaire.phtml', array('types' => $this->DB_type, 'activites' => $this->DB_activite)) ?>
                      <?php if($this->etablissement['types_activites_secondaires']) : ?>
                      <?php foreach($this->etablissement['types_activites_secondaires'] as $type_activite_secondaire) : ?>
                          <?php echo $this->partial('etablissement/partials/partial-type-activites-secondaire.phtml', array('type_activite_secondaire' => $type_activite_secondaire, 'types' => $this->DB_type, 'activites' => $this->DB_activite)) ?>
                      <?php endforeach ?>
                      <?php endif ?>
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label">R123-20 ?</label>
                <div class="col-sm-9">
                  <input type='hidden' name='R12320_ETABLISSEMENTINFORMATIONS' value='0' />
                  <input type='checkbox' name='R12320_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["R12320_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> />
                </div>
              </div>

              <div class="form-group champs champ_localsommeil">
                <label class="col-sm-3 control-label">Local à sommeil ?</label>
                <div class="col-sm-9">
                  <input type='radio' name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS' value='0' <?php if( !$this->add ) echo "checked" ?> /> Non
                  <input type='radio' name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS' value='1' <?php if( $this->etablissement['informations']["LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"] ) echo "checked" ?> /> Oui
                </div>
              </div>
            </div>

            <!-- Rubriques -->
            <h3 class='champs_icpe champs rubrique '>Rubriques ICPE <a href='#' style='font-size: 14px; line-height: 24px; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_rubriques').clone().appendTo( $(this).parent().next() ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); return false;">Ajouter une rubrique</a></h3>
            <table class='table table-condensed champs_icpe champs rubrique'>
                <thead>
                    <tr>
                        <th>Rubrique</th>
                        <th>Numéro</th>
                        <th>Nom</th>
                        <th>Valeur</th>
                        <th>Classement</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Rubriques -->
                    <?php echo $this->partial('etablissement/partials/partial-rubrique.phtml') ?>
                    <?php if($this->etablissement['rubriques']) : ?>
                    <?php foreach($this->etablissement['rubriques'] as $rubrique) : ?>
                        <?php echo $this->partial('etablissement/partials/partial-rubrique.phtml', array('rubrique' => $rubrique)) ?>
                    <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>

            <!-- Les effectifs -->
            <h3 class='champ_effectifs champs '>Les effectifs</h3>
            <div class='champ_effectifs champs'>
                <!-- Effectif public -->
                <div class="form-group">
                  <label class="col-sm-3 control-label">Public</label>
                  <div class="col-sm-9">
                    <input class='form-control' type='text' name='NUMEROID_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["NUMEROID_ETABLISSEMENT"]?>' />
                  </div>
                </div>

                <!-- Effectif personnel -->
                <div class="form-group">
                  <label class="col-sm-3 control-label">Personnel</label>
                  <div class="col-sm-9">
                    <input type='text' class='form-control' name='EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"] ?>' />
                  </div>
                </div>

                <!-- Effectif hebergé -->
                <div class="form-group effectif_heberge">
                  <label class="col-sm-3 control-label">Dont hébergé</label>
                  <div class="col-sm-9">
                    <input type='text' class='form-control' name='EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS"] ?>' />
                  </div>
                </div>

                <!-- Effectif justifant le classement (que pour les 5ème catégorie) -->
                <div class="form-group effectif_justifiant_classement">
                  <label class="col-sm-3 control-label">Justifiant le classement</label>
                  <div class="col-sm-9">
                    <input type='text' class='form-control' name='EFFECTIFJUSTIFIANTCLASSEMENT_ETABLISSEMENTINFORMATIONS' value='<?php echo $this->etablissement['informations']["EFFECTIFJUSTIFIANTCLASSEMENT_ETABLISSEMENTINFORMATIONS"] ?>' />
                  </div>
                </div>
            </div>

            <!-- Plan -->
            <h3 class="champ_plans champs ">Plans d'intervention <a href='#' style='font-size: 14px; line-height: 24px; float: right; font-weight: normal;' onclick="time = Date.now(); $('#prototype_plan').clone().appendTo( $(this).parent().next() ).removeClass('hide prototypes').attr('id', '').find('input, select').each(function() {$(this).attr('name', $(this).attr('name').replace(/-1/gi, time)); }); return false;">Ajouter un plan</a></h3>
            <table class='table table-condensed champ_plans champs'>
                <thead>
                    <tr>
                        <th>Type de plan</th>
                        <th>Numéro du plan</th>
                        <th>Date</th>
                        <th>A mettre à jour</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo $this->partial('etablissement/partials/partial-plan.phtml', array('types_plans' => $this->DB_typesplan)) ?>
                    <?php if($this->etablissement['plans']) : ?>
                    <?php foreach($this->etablissement['plans'] as $plan) : ?>
                        <?php echo $this->partial('etablissement/partials/partial-plan.phtml', array('plan' => $plan, 'types_plans' => $this->DB_typesplan)) ?>
                    <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>

            <!-- Etablissement lié -->
            <h3>Établissements liés <?php if($this->etablissement['general']) : ?> <a id='add_etablissement' href='<?php echo $this->url(array(), 'ets_add', true)?>?pere=<?php echo $this->etablissement['general']['ID_ETABLISSEMENT'] ?>&libelle=<?php echo htmlspecialchars($this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES) ?>' class='edit' style='font-size: 14px; line-height: 24px; float: right; font-weight: normal;' >Créer un établissement enfant</a> <?php endif ?></h3>
            <div>
              <div class="form-group etablissement_pere">
                <label class="col-sm-3 control-label">Père de l'établissement</label>
                <div class="col-sm-9">
                  <select name='ID_PERE'>
                    <?php if(count($this->etablissement['parents']) > 0) : ?>
                      <option value='<?php echo end($this->etablissement['parents'])["ID_ETABLISSEMENT"] ?>' selected>
                        <?php echo htmlspecialchars(end($this->etablissement['parents'])["LIBELLE_ETABLISSEMENTINFORMATIONS"], ENT_QUOTES); ?>
                      </option>
                    <?php elseif( isset($_GET["libelle"]) ) : ?>
                      <option value='<?php echo $_GET["pere"] ?>' selected>
                        <?php echo htmlspecialchars($_GET["libelle"], ENT_QUOTES) ?>
                      </option>
                    <?php endif ?>
                  </select>
                </div>
              </div>

              <div class="form-group etablissements_enfants">
                <label class="col-sm-3 control-label">Enfants de l'établissement</label>
                <div class="col-sm-9">
                  <select name='ID_FILS_ETABLISSEMENT[]' multiple>
                    <?php if($this->etablissement['etablissement_lies']) : ?>
                      <?php foreach( $this->etablissement['etablissement_lies'] as $etablissement ) : ?>
                          <option value='<?php echo $etablissement["ID_ETABLISSEMENT"] ?>' selected>
                            <?php echo $etablissement["LIBELLE_ETABLISSEMENTINFORMATIONS"] ?>
                          </option>
                      <?php endforeach ?>
                    <?php endif ?>
                  </select>
                </div>
              </div>

            </div>
        </div>

        <!-- Carte de l'emplacement de l'établissement / informations  -->
        <div class='col-xs-6'>
            <?php if( false && count($this->etablissement['adresses']) > 0 && $this->key_ign != null && $this->etablissement['adresses'][0]['LAT_ETABLISSEMENTADRESSE'] != null && $this->etablissement['adresses'][0]['LON_ETABLISSEMENTADRESSE'] != null) : ?>
                <div id='geoportail-container' style="height: 350px; max-height: 350px;"></div>
            <?php endif ?>
            <h3 class="champ_adresse champs ">Adresse <a style='font-size: 14px; line-height: 24px; float: right; font-weight: normal;' data-toggle="modal" data-backdrop="false" href="#adresse-modal">Ajouter une adresse</a></h3>
            <table id='adresses' class='table table-condensed champ_adresse champs'>
                <thead>
                    <tr>
                        <th>Localisation</th>
                        <th>Type</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo $this->partial('etablissement/partials/partial-adresse.phtml') ?>
                    <?php if($this->etablissement['adresses']) : ?>
                    <?php foreach( $this->etablissement['adresses'] as $adresse ) : ?>
                        <?php echo $this->partial('etablissement/partials/partial-adresse.phtml', array('adresse' => $adresse)) ?>
                    <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>

            <h3>Coordonnées</h3>
            <div>
                <!-- Téléphone -->
                <div class="form-group">
                  <label class="col-sm-3 control-label">Téléphone</label>
                  <div class="col-sm-9">
                    <input class='form-control' type='text' name='TELEPHONE_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["TELEPHONE_ETABLISSEMENT"] ?>' />
                  </div>
                </div>

                <!-- Fax -->
                <div class="form-group">
                  <label class="col-sm-3 control-label">Fax</label>
                  <div class="col-sm-9">
                    <input class='form-control' type='text' name='FAX_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["FAX_ETABLISSEMENT"] ?>' />
                  </div>
                </div>

                <!-- Courriel -->
                <div class="form-group">
                  <label class="col-sm-3 control-label">Courriel</label>
                  <div class="col-sm-9">
                    <input class='form-control' type='text' name='COURRIEL_ETABLISSEMENT' value='<?php echo $this->etablissement['general']["COURRIEL_ETABLISSEMENT"] ?>' />
                  </div>
                </div>
            </div>

            <h3>Données prévention</h3>
            <div>
                <!-- Commission compétente -->
                <div class="form-group champ_commission champs">
                  <label class="col-sm-3 control-label">Commission compétente</label>
                  <div class="col-sm-9">
                    <select name='ID_COMMISSION' class='form-control' >
                        <?php foreach( $this->DB_commission as $item ) : ?>
                            <option value='<?php echo $item["ID_COMMISSION"] ?>' <?php if( $item["ID_COMMISSION"] == $this->etablissement['informations']["ID_COMMISSION"] ) echo "selected" ?> ><?php echo $item["LIBELLE_COMMISSION"] ?></option>
                        <?php endforeach ?>
                    </select>
                  </div>
                </div>

                <!-- Préventionnistes -->
                <div class="form-group preventionnistes">
                  <label class="col-sm-3 control-label">Préventionnistes</label>
                  <div class="col-sm-9">
                    <select name='ID_UTILISATEUR[]' multiple>
                      <?php if($this->etablissement['preventionnistes']) : ?>
                        <?php foreach( $this->etablissement['preventionnistes'] as $preventionniste ) : ?>
                            <option selected value='<?php echo $preventionniste["ID_UTILISATEUR"] ?>'>
                              <?php echo $preventionniste["NOM_UTILISATEURINFORMATIONS"]." ".$preventionniste["PRENOM_UTILISATEURINFORMATIONS"] ?>
                            </option>
                        <?php endforeach ?>
                      <?php endif ?>
                    </select>
                  </div>
                </div>

                <!-- Données pratiques -->
                <div class="form-group champ_donnees_pratiques champs">
                  <label class="col-sm-3 control-label">Données pratiques</label>
                  <div class="col-sm-9">
                    <label>Nb. de préventionnistes/visite</label>
                    <input class='form-control' type='number'  name='NBPREV_ETABLISSEMENT' value='<?php echo $this->etablissement['donnees_pratiques']["NBPREV_ETABLISSEMENT"] ?>' />
                    <label>Durée d'une visite</label>
                    <input class='form-control' type='time' name='DUREEVISITE_ETABLISSEMENT' value='<?php echo $this->etablissement['donnees_pratiques']["DUREEVISITE_ETABLISSEMENT"] ?>' />
                  </div>
                </div>

            </div>

        </div>

    </div>

</form>

<!-- Boite de confirmation de l'édition (cachée par défaut) -->
<div id="confirm-modal" class="modal fade" >

  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class='modal-title'>Confirmation de l'édition</h4>
      </div>

      <div class="modal-body">
          <dl>
              <dt>Date d'enregistrement de la fiche d'informations</dt>
              <dd id='confirm-modal-date'><span class='confirm-modal-input'></span> <span class='label label-info hide'>Fiche d'informations déjà existante</span></dd>
          </dl>

          <dl>
              <dt>Valeurs conseillées</dt>
              <dd>
                  <ul>
                      <li id='confirm-modal-commission'>Commission renseignée : <a href="#" class='label label-info confirm-modal-input'>Aucune</a>, la commission conseillée : <a href="#" class='label label-default confirm-modal-advisable'></a></li>
                      <li id='confirm-modal-periodicite'>Périodicité renseignée : <a href="#" class='label label-info confirm-modal-input'>Aucune</a>, la périodicité conseillée : <a href="#" class='label label-default confirm-modal-advisable'></a></li>
                      <li id='confirm-modal-localsommeil'>Présence de local à sommeil renseignée : <a href="#" class='label label-info confirm-modal-input'></a>, la présence conseillée : <a href="#" class='label label-default confirm-modal-advisable'></a></li>
                      <li id='confirm-modal-preventionnistes' >Préventionnistes affectés : <a href="#" class='label confirm-modal-input label-info'>Aucuns</a>, les préventionnistes conseillés : <a href="#" class='label label-default confirm-modal-advisable'></a></li>
                  </ul>
              </dd>
          </dl>
      </div>

      <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Annuler</a>
          <input type='submit' value='Confirmer et sauvegarder les changements' class='btn btn-success' />
      </div>

    </div>

  </div>

</div>

<!-- Boite de construction d'adresse-->
<form id="adresse-modal" class="modal adresse fade form-horizontal" action='<?php echo $this->url(array('action' => 'add')) ?>' method='post' >

  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class='modal-title'>Ajouter une adresse</h4>
      </div>

      <div class="modal-body">

        <div class="form-group">
          <label class="col-sm-3 control-label">Ville</label>
          <div class="col-sm-9">
            <select class='adresse_commune' placeholder='Nom de la commune ou code postal ...'></select>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Voie</label>
          <div class="col-sm-9">
            <select class='adresse_voie' placeholder='Nom de la voie ...' disabled ></select>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Numéro</label>
          <div class="col-sm-9">
            <input type='text' class='adresse_numero form-control' placeholder='Numéro ...' disabled />
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Complément d'adresse</label>
          <div class="col-sm-9">
            <input type='text' class='adresse_complement form-control' placeholder="Complément d'adresse" disabled />
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Type de l'adresse</label>
          <div class="col-sm-9">
            <p class="form-control-static">Adresse postale</p>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Géolocalisation</label>
          <div class="col-sm-9">
            Longitude: <span class='lon'>Inconnu</span>; Latitude: <span class='lat'>Inconnu</span>
            <button id="geolocme" class='btn btn-default btn-small'>Géolocaliser cette adresse</button>
            <input type='hidden' name='adresse_lon' />
            <input type='hidden' name='adresse_lat' />
          </div>
        </div>

      </div>

      <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Annuler</a>
          <input type='submit' id='submit' value='Sauvegarder' class='btn btn-success' />
      </div>

    </div>

  </div>

</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {

        // Action à la sauvegarde de l'établissement
        $("form#etablissement input[type='submit']").click(function() {
            // On va chercher les valeurs par défauts pour faire apparaitre la boite de confirmation
            var etablissements_enfants = [];
            $("table#etablissements_enfants tbody tr.etablissement_enfant").each(function(index) { etablissements_enfants[index] = $(this).find('input[name="ID_FILS_ETABLISSEMENT[]"]').first().val(); });
            $.getJSON('/api/1.0/etablissement/defaults_values', {
                genre: $("select[name='ID_GENRE']").find('option:selected').val(),
                numinsee: $("#adresses").find('tr.adresse').first().find('input[type="hidden"]').first().val(),
                type: $("select[name='ID_TYPE']").find('option:selected').val(),
                categorie: $("select[name='ID_CATEGORIE']").find('option:selected').val(),
                local_sommeil: $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").is(':checked'),
                classe: $("select[name='ID_CLASSE']").find('option:selected').val(),
                id_etablissement_pere: $("input[name='ID_PERE']").val(),
                ids_etablissements_enfants: etablissements_enfants
            }, function(data) {
                // Si il y a des données disponibles dans les valeurs par défauts proposées, on ouvre la boite de confirmation, sinon on sauvegarde la fiche
                if(data.status == 'success' && Object.keys(data.response).length > 0) {
                    // A l'apparition de la boite de confirmation on met à jour les valeurs saisies par l'utilisateur dans la boite
                    var preventionnistes = [];
                    var date = new Date();
                    $('#confirm-modal-commission .confirm-modal-input').text($('select[name="ID_COMMISSION"] option:selected').text());
                    $('#confirm-modal-periodicite .confirm-modal-input').text($('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').val());
                    $('#confirm-modal-localsommeil .confirm-modal-input').text($('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"][value=1]').is(':checked') ? 'Oui' : 'Non' );
                    $("select[name='ID_UTILISATEUR[]']").next().find('.item').each(function(index) { preventionnistes[index] = $(this).text(); });
                    $('#confirm-modal-preventionnistes .confirm-modal-input').text(preventionnistes.toString() == '' ? 'Aucuns' : preventionnistes.toString());
                    $('#confirm-modal-date .confirm-modal-input').text(date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear());
                    // On met à jour les valeurs par défauts
                    $('#confirm-modal-commission .confirm-modal-advisable').attr('id', data.response.commission ? data.response.commission.ID_COMMISSION : '').text(data.response.commission ? data.response.commission.LIBELLE_COMMISSION : '');
                    $('#confirm-modal-periodicite .confirm-modal-advisable').text(data.response.periodicite);
                    $('#confirm-modal-localsommeil .confirm-modal-advisable').text(data.response.local_sommeil && data.response.local_sommeil == true ? 'Oui' : 'Non');
                    if(data.response.preventionnistes && data.response.preventionnistes.length > 0) {
                        var preventionnistes = [];
                        var preventionnistes_ids = [];
                        for(var x in data.response.preventionnistes) {
                            preventionnistes[x] = data.response.preventionnistes[x].nom + ' ' + data.response.preventionnistes[x].prenom;
                            preventionnistes_ids[x] = data.response.preventionnistes[x].uid;
                        }
                        $('#confirm-modal-preventionnistes .confirm-modal-advisable').attr('ids', preventionnistes_ids.toString()).text(preventionnistes.toString());
                    }
                    $('#confirm-modal').find('li').removeClass('confirm-modal-hide');
                    $('#confirm-modal').find('li').each(function(index) {
                        if($(this).find('.confirm-modal-input').text() == $(this).find('.confirm-modal-advisable').text() || $(this).find('.confirm-modal-advisable').text() == '') {
                            $(this).addClass("confirm-modal-hide");
                        }
                    });
                    if($('#confirm-modal').find('li.confirm-modal-hide').length == 4) {
                        $("form#etablissement").submit();
                    }
                    else {
                        $('#confirm-modal').modal({show: true});
                    }
                }
                else {
                    $("form#etablissement").submit();
                }
            });
            return false;
        });

        // Comportement des labels interactifs dans la boite de confirmation
        $('#confirm-modal a.label').click(function() {
            $(this).parent().find('a.label').toggleClass('label-info');
            $(this).parent().find('a.label').toggleClass('label-default');
        });

        // Gestion de la prise en compte des valeurs par défaut dans la boite de confirmation
        $('#confirm-modal input[type="submit"]').click(function() {
            $('#confirm-modal').find('a.label-info').each(function(index) {
                if($(this).hasClass('confirm-modal-advisable')) {
                    switch($(this).parent().prop('id')) {
                        case 'confirm-modal-preventionnistes':
                            $("select[name='ID_UTILISATEUR[]']").remove();
                            var preventionnistes_ids = $(this).attr('ids').split(",");
                            for(var x in preventionnistes_ids) {
                                $('<input>').attr({type: 'hidden', name: 'ID_UTILISATEUR[]', value: preventionnistes_ids[x]}).appendTo('form#etablissement');
                            }
                            break;
                        case 'confirm-modal-commission':
                            $('select[name="ID_COMMISSION"]').find('option[value=' + $(this).prop('id') + ']').attr('selected', true);
                            break;
                        case 'confirm-modal-periodicite':
                            $('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').val($(this).text());
                            break;
                        case 'confirm-modal-localsommeil':
                            $('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"][value=1]').attr('checked', $(this).text() == 'Oui');
                            break;
                    }
                }
            });

            $("form#etablissement").submit();
        });

        // Ajout d'une adresse
        $(document).on('click', "form.adresse input[type='submit']", function() {
            time = Date.now();
            node = $('#prototype_adresse').clone().prependTo( $('table.champ_adresse') ).removeClass('hide prototypes').addClass('adresse').attr('id', '');
            node.find('input[name="ADRESSES[-1][LON_ETABLISSEMENTADRESSE]"]').val($('form.adresse').find('input[name="lon"]').val());
            node.find('input[name="ADRESSES[-1][LAT_ETABLISSEMENTADRESSE]"]').val($('form.adresse').find('input[name="lat"]').val());
            node.find('input[name="ADRESSES[-1][NUMERO_ADRESSE]"]').val($('form.adresse').find('input[name="numero"]').val());
            node.find('input[name="ADRESSES[-1][ID_RUE]"]').val($('form.adresse').find('input[name="voie"]').val());
            node.find('input[name="ADRESSES[-1][NUMINSEE_COMMUNE]"]').val($('form.adresse').find('input[name="code_insee"]').val());
            node.find('input[name="ADRESSES[-1][COMPLEMENT_ADRESSE]"]').val($('form.adresse').find('input[name="complement"]').val());
            node.find('span').text($('form.adresse').find('input[name="numero"]').val() + " " + $('form.adresse').find('input[name="voie_ac"]').val() + " " + $('form.adresse').find('input[name="code_postal"]').val() + " " + $('form.adresse').find('input[name="commune_ac"]').val());
            node.find('input').each(function() {$(this).attr('name', $(this).prop('name').replace(/-1/gi, time)); });
            $('form.adresse').find('button.close').click();
            return false;
        });

        // Action sur le changement du genre (affichage des champs)
        $("select[name='ID_GENRE']").change(function() {
            $('.champs').hide();
            $('.etablissement_pere, .etablissements_enfants').show();
            switch($(this).find('option:selected').val()) {
                // Site
                case '1':
                    $('.etablissement_pere').hide();
                    break;

                // Établissement
                case '2':
                    $('.champ_categorie, .champ_periodicite, .champ_types, .champ_effectifs, .champ_plans, .champ_adresse, .champ_commission, .champ_localsommeil, .champ_donnees_pratiques').show();
                    break;

                // Cellule
                case '3':
                    $('.champ_types, .champ_effectifs, .champ_plans, .champ_donnees_pratiques').show();
                    $('.etablissements_enfants').hide();
                    break;

                // Habitation
                case '4':
                    $('.champ_famille, .champ_adresse').show();
                    $('.etablissements_enfants').hide();
                    break;

                // IGH
                case '5':
                    $('.champ_periodicite, .champ_classe, .champ_effectifs, .champ_plans, .champ_adresse, .champ_commission, .champ_donnees_pratiques').show();
                    $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").attr('checked', false).change();
                    break;

                // EIC
                case '6':
                    $('.champ_icpe, .champ_effectifs, .champ_plans, .champ_adresse').show();
                    $('.etablissements_enfants, .effectif_heberge, .effectif_public').hide();
                    $("input[name='ICPE_ETABLISSEMENTINFORMATIONS']").change();
                    $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").attr('checked', false).change();
                    break;
            }
        }).change();

        // Actions sur le changement de type principal
        $("select[name='ID_TYPE']").change(function() {
            // Si l'établissement est un parking, alors l'effectif public est le nombre de places de stationnement
            if($(this).val() == '16') {
                $("dt.effectif_public").html('Places de stationnement');
            }
        }).change();

        // Actions sur le changement de catégorie
        $("select[name='ID_CATEGORIE']").change(function() {
            // Gestion de l'affichage de l'effectif justifiant le classement (uniquement pour les 5ème catégorie)
            if($(this).val() == 5) {
                $(".effectif_justifiant_classement").show();
            } else {
                $(".effectif_justifiant_classement").hide().find("input").val("");
            }
        }).change();

        // Actions sur le statut ICPE
        $("input[name='ICPE_ETABLISSEMENTINFORMATIONS']").change(function() {
            if( $(this).is(":checked") && $("select[name='ID_GENRE'] option:selected").val() == 6 ) {
                $(".rubrique").show();
            } else {
                $(".rubrique").hide();
            }
        }).change();

        // Affichage ou non de l'effectif hebergé en fonction de la checkbox local sommeil
        $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS']").change(function() {
            if( $("input[name='LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'][value=1]").is(":checked") )
                $(".effectif_heberge").show();
            else
                $(".effectif_heberge").hide();
        }).change();

        // Fonction pour afficher les activités du type
        $(document).on("change", "select.type_select", function() {
            activites = <?php echo Zend_Json::encode($this->DB_activite) ?>;
            $(this).next().find("option").remove();
            for( var x in activites) {
                if( activites[x]["ID_TYPE"] == $(this).val() ) {
                    $(this).next().append($("<option />").val(activites[x]["ID_TYPEACTIVITE"]).text(activites[x]["LIBELLE_ACTIVITE"]));
                }
            }
        })

        // On choisit d'initialiser ou de remettre à 0 les activités en fonction du type
        $("select.type_select").each(function(index) {
            if($(this).next().find("option").length == 0) {
                $(this).change();
            }
        });

        // Géolocalisation de l'adresse
        $('#adresse-modal button#geolocme').click(function() {
            element = $(this);
            $.ajax({
                url: "http://nominatim.openstreetmap.org/search",
                dataType: 'json',
                timeout: 10000,
                data: {
                    format: "json",
                    limit: 1,
                    country: "France",
                    street: $("input.adresse_numero").val() + " " + $(".selectize-control.adresse_voie .item").text(),
                    city: $(".selectize-control.adresse_commune .item").text(),
                    postalcode: $("select.adresse_commune").val().substring(0,2)
                },
                beforeSend: function() {
                    element.text("Géolocalisation en cours ...");
                },
                success: function(geolocations) {
                    element.text("Géolocaliser cette adresse");
                    if(geolocations.length > 0) {
                        $("input[name='lon']").val(geolocations[0].lon);
                        $("span.lon").text(geolocations[0].lon);
                        $("input[name='lat']").val(geolocations[0].lat);
                        $("span.lat").text(geolocations[0].lat);
                    }
                    else {
                        $("input[name='lon']").val(0);
                        $("span.lon").text("Introuvable");
                        $("input[name='lat']").val(0);
                        $("span.lat").text("Introuvable");
                    }
                },
                error: function() {
                    element.text("Serveur de géolocalisation introuvable").attr('disabled', true);
                }
            });
            return false;
        });

        // Auto-complétion des préventionnistes
        $("select[name='ID_UTILISATEUR[]']").selectize({
          valueField: 'id',
          labelField: 'name',
          searchField: 'name',
          load: function(query, callback) {
            if (!query.length) return callback();
            $.getJSON('/api/1.0/search/users', {name: query, fonction: 13}, function(data) {
              matches = [];
              $.map(data.response.results, function(item) {
                matches.push({ name: item.NOM_UTILISATEURINFORMATIONS + ' ' + item.PRENOM_UTILISATEURINFORMATIONS, id: item.uid });
              });
              callback(matches);
            });
          },
          onDropdownOpen: function() {$(".selectize-dropdown").stop().show();},
          onDropdownClose: function() {$(".selectize-dropdown").stop().hide();}
        });

        // Auto-complétion de l'établissement père
        $("select[name='ID_PERE']").selectize({
          valueField: 'id',
          labelField: 'name',
          searchField: 'name',
          load: function(query, callback) {
            if (!query.length) return callback();
            $.getJSON('/api/1.0/search/etablissements', {label: query}, function(data) {
              matches = [];
              $.map(data.response.results, function(item) {
                matches.push({ genre: item.LIBELLE_GENRE, commune: item.LIBELLE_COMMUNE, name: item.LIBELLE_ETABLISSEMENTINFORMATIONS, id: item.ID_ETABLISSEMENT });
              });
              callback(matches);
            });
          },
          render: {
            option: function(item, escape) {
              return '<div>' +
                  '<strong>' + escape(item.name) + '</strong><br>' +
                  (item.genre && item.commune ? '<small>Genre : ' + escape(item.genre) + ' - Commune : ' + escape(item.commune) + '</small>' : '') +
              '</div>';
            }
        },
          onDropdownOpen: function() {$("select[name='ID_PERE']").next().find(".selectize-dropdown").stop().show();},
          onDropdownClose: function() {$("select[name='ID_PERE']").next().find(".selectize-dropdown").stop().hide();}
        });

        // Auto-complétion des établissements enfants
        $("select[name='ID_FILS_ETABLISSEMENT[]']").selectize({
          valueField: 'id',
          labelField: 'name',
          searchField: 'name',
          load: function(query, callback) {
            if (!query.length) return callback();
            $.getJSON('/api/1.0/search/etablissements', {label: query}, function(data) {
              matches = [];
              $.map(data.response.results, function(item) {
                matches.push({ genre: item.LIBELLE_GENRE, commune: item.LIBELLE_COMMUNE, name: item.LIBELLE_ETABLISSEMENTINFORMATIONS, id: item.ID_ETABLISSEMENT });
              });
              callback(matches);
            });
          },
          render: {
            option: function(item, escape) {
              return '<div>' +
                  '<strong>' + escape(item.name) + '</strong><br>' +
                  (item.genre && item.commune ? '<small>Genre : ' + escape(item.genre) + ' - Commune : ' + escape(item.commune) + '</small>' : '') +
              '</div>';
            }
          },
          onDropdownOpen: function() {$("select[name='ID_FILS_ETABLISSEMENT[]']").next().find(".selectize-dropdown").stop().show();},
          onDropdownClose: function() {$("select[name='ID_FILS_ETABLISSEMENT[]']").next().find(".selectize-dropdown").stop().hide();}
        });

        // Auto complétion de la ville
        $("select.adresse_commune").selectize({
          valueField: 'id',
          labelField: 'name',
          searchField: 'name',
          load: function(query, callback) {
            if (!query.length) return callback();
            $.getJSON('/api/1.0/adresse/get_communes', {q: query}, function(data) {
              matches = [];
              $.map(data.response, function(item) {
                matches.push({ name: item.LIBELLE_COMMUNE, id: item.NUMINSEE_COMMUNE });
              });
              callback(matches);
            });
          },
          onChange: function(value) {
            if (value > 0) {
              $("select.adresse_voie")[0].selectize.enable();
            }
            else {
              $("select.adresse_voie")[0].selectize.disable();
              $("input.adresse_numero, input.adresse_complement").attr("disabled", true);
            }
          },
          onDropdownOpen: function() {$("select.adresse_commune").next().find(".selectize-dropdown.adresse_commune").stop().show();},
          onDropdownClose: function() {$("select.adresse_commune").next().find(".selectize-dropdown.adresse_commune").stop().hide();}
        });

        // Auto complétion de la rue
        $("select.adresse_voie").selectize({
          valueField: 'id',
          labelField: 'name',
          searchField: 'name',
          load: function(query, callback) {
            if (!query.length) return callback();
            $.getJSON('/api/1.0/adresse/get_voies', {code_insee: $("select.adresse_commune option:selected").val(), q: query}, function(data) {
              matches = [];
              $.map(data.response, function(item) {
                matches.push({ name: item.LIBELLE_RUE, id: item.ID_RUE });
              });
              callback(matches);
            });
          },
          onChange: function(value) {
            if (value > 0) {
              $("input.adresse_numero, input.adresse_complement").attr("disabled", false);
            }
            else {
              $("input.adresse_numero, input.adresse_complement").attr("disabled", true);
            }
          },
          onDropdownOpen: function() {$("select.adresse_voie").next().find(".selectize-dropdown.adresse_voie").stop().show();},
          onDropdownClose: function() {$("select.adresse_voie").next().find(".selectize-dropdown.adresse_voie").stop().hide();}
        });

    });
</script>
