<?php echo $this->render('etablissement/partials/header.phtml') ?>

<h2>Historique</h2>

<?php if(array_key_exists('avis', $this->historique)) : ?>
<h3>Historique des avis d'exploitation</h3>
<?php
    if(isset($this->historique["avis"]))
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["avis"]
    ));
    else
    echo "Pas d'historique disponible.";
?>
<?php endif ?>

<h3>Historique du libellé</h3>
<?php
    if(isset($this->historique["LIBELLE_ETABLISSEMENTINFORMATIONS"]))
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["LIBELLE_ETABLISSEMENTINFORMATIONS"]
    ));
    else
    echo "Pas d'historique disponible.";
?>

<h3>Historique du statut</h3>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_STATUT"]
    ));
?>

<h3>Historique de la catégorie</h3>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml",array(
        "array" => $this->historique["ID_CATEGORIE"]
    ));
?>

<h3>Historique de la classe</h3>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_CLASSE"]
    ));
?>


<h3>Historique de la famille</h3>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_FAMILLE"]
    ));
?>

<h3>Historique du type d'activité</h3>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_TYPE"]
    ));
?>
