<?php echo $this->render('etablissement/partials/header.phtml') ?>

<div class='pull-right' >
    <a class='btn btn-default' href="<?php echo $this->url(array('id' => $this->etablissement['general']['ID_ETABLISSEMENT']), 'ets_textes_applicables_edit', true) ?>">Modifier les textes applicables</a>
</div>

<h2>Textes applicables</h2>

<?php if(count($this->textes_applicables_de_etablissement) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de texte applicable.</p>
        <p><a href='<?php echo $this->url(array('id' => $this->etablissement['general']['ID_ETABLISSEMENT']), 'ets_textes_applicables', true) ?>' class='btn btn-default btn-large'>Gérer les textes applicables</a></p>
    </div>

<?php else : ?>

<div class='row-fluid'>
    <?php foreach($this->textes_applicables_de_etablissement as $titre => $textes_applicables) : ?>
        <h3><?php echo $titre ?></h3>
        <ul class='list-unstyled'>
            <?php foreach($textes_applicables as $texte_applicable) : ?>
                <li>
                    ✓ <?php echo $texte_applicable['LIBELLE_TEXTESAPPL'] ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
</div>

<?php endif ?>
