<!doctype html>
<html lang="fr" >

    <head>

        <?php echo $this->render("includes/header.phtml"); ?>

        <style>
          html, body {
            height: 100%;
          }
          .wrapper {
            display: table;
            height: 100%;
            width: 100%;
          }
          .block {
            display: table-cell;
            vertical-align: middle;
          }
          .well {
            padding: 20px;
            margin: 50px auto 50px auto;
            max-width: 350px;
            text-align: center;
          }
          .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
          }
          .form-signin .form-signin-heading,
          .form-signin .checkbox {
            margin-bottom: 10px;
          }
          .form-signin .checkbox {
            font-weight: normal;
          }
          .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
               -moz-box-sizing: border-box;
                    box-sizing: border-box;
            padding: 7px;
          }
          .form-signin .form-control:focus {
            z-index: 2;
          }
          .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
          }
          .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
          }
          footer {
            text-align: center;
            font-size: .8em;
            border: none;
            padding: 0;
            margin: 0;
            width: auto;
            background-color: white;
          }
          footer a {
            color: #999999;
          }
          footer a:hover {
            color: #404040;
          }
          footer:hover a {
            color: #404040;
          }
        </style>

    </head>

    <body>

        <div class="wrapper">

          <div class="block">

            <h1 class='text-center animated fadeInDown'>
              <img src='/assets/img/logo_prevarisc_big.jpg' />
            </h1>

            <div class='well'>

              <?php echo $this->render("includes/notifications.phtml"); ?>

              <?php echo $this->layout()->content; ?>

            </div>

            <?php echo $this->render("includes/footer.phtml"); ?>

          </div>

        </div>


        <?php echo $this->inlineScript() ?>

    </body>

</html>
