<div class='dashboard'>

  <div class="grid-sizer"></div>
  <div class="grid-gutter"></div>

  <div id="reponse-modal" class="modal fade" ></div>

  <!-- Alerte : Etablissements sous avis défavorables -->
  <?php if( count($this->etablissementAvisDefavorable) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Alerte : Etablissements sous avis défavorable
    </div>
    <div class="panel-body panel-body-heightlimit">
      <ul class='search-list'>
      <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->etablissementAvisDefavorable ) ?>
      </ul>
      <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Alerte : Etablissements sous avis défavorables -->
  <?php if( count($this->erpSansPreventionniste) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Alerte : Etablissements sans préventionnistes
    </div>
    <div class="panel-body panel-body-heightlimit">
      <ul class='search-list'>
      <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->erpSansPreventionniste ) ?>
      </ul>
      <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Courrier sans réponse -->
  <?php if( count($this->CourrierSansReponse) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Alerte : Courriers sans réponse
    </div>
    <div class="panel-body panel-body-heightlimit">
      <ul class='search-list'>
      <?php echo $this->partialLoop('search/results/dossier.phtml', $this->CourrierSansReponse ) ?>
      </ul>
      <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Alerte : Dossiers sans avis de la commission échue -->
  <?php if( count($this->dossierCommissionEchu) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Alerte : Dossiers sans avis de la commission échue
    </div>
    <div class="panel-body panel-body-heightlimit">
      <ul class='search-list'>
      <?php echo $this->partialLoop('search/results/dossier.phtml', $this->dossierCommissionEchu ) ?>
      </ul>
      <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Alerte : Etablissements sans prochaine visite périodique programmée (sous 3 mois) -->
  <?php if( count($this->ErpSansProchaineVisitePeriodeOuvert) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Alerte : Etablissements sans prochaine visite périodique programmée (sous 3 mois)
    </div>
    <div class="panel-body panel-body-heightlimit">
      <ul class='search-list'>
      <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->ErpSansProchaineVisitePeriodeOuvert ) ?>
      </ul>
      <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Messages -->
  <div class="panel panel-default">
    <div class="panel-heading">
      Messages
      <a class='btn btn-default btn-sm pull-right' style='margin-top: -4px;' data-toggle="modal" data-target="#reponse-modal" href='<?php echo $this->url(array('controller' => 'news', 'action' => 'add')) ?>'>Ajouter un message</a>
    </div>
    <div class="panel-body panel-body-heightlimit">
      <?php if( count($this->flux) == 0 ) : ?>
          <p class='muted'><small>Aucun message disponible.</small></p>
      <?php else : ?>
          <table class='table table-condensed'>
           <?php echo $this->partialLoop('news/partials/partial-display.phtml', $this->flux); ?>
          </table>
      <?php endif ?>
    </div>
  </div>

  <!-- Etablissements suivis -->
  <?php if( count($this->etablissements) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Etablissements suivis
    </div>
    <div class="panel-body panel-body-heightlimit">
        <ul class='search-list'>
        <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->etablissements ) ?>
        </ul>
        <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Dossiers avec un avis différé -->
  <?php if( count($this->dossiers) > 0 ) : ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      Dossiers avec un avis différé
    </div>
    <div class="panel-body panel-body-heightlimit">
        <ul class='search-list'>
        <?php echo $this->partialLoop('search/results/dossier.phtml', $this->dossiers ) ?>
        </ul>
        <div style='clear: both'></div>
    </div>
  </div>
  <?php endif ?>

  <!-- Ordre du jour -->
  <?php if( count($this->commissions) > 0 ) : ?>
  <div class="panel panel-default w2">
    <div class="panel-heading">
      Ordre du jour
    </div>
    <div class="panel-body panel-body-heightlimit">
      <?php foreach($this->commissions as $commission) : ?>
        <p><?php echo strtoupper($commission["name"]) . " du " . $commission["date"] . " (" . $commission["heure"] . ")" ?></p>
        <?php if(count($commission["odj"]) == 0 ) : ?>
          <p class="muted">Pas de dossier affecté.</p>
        <?php else : ?>
          <ul class='search-list'>
            <?php echo $this->partialLoop('search/results/dossier.phtml', $commission["odj"] ) ?>
          </ul>
        <?php endif ?>
      <?php endforeach ?>
      <div style='clear: both'></div>
  </div>
  <?php endif ?>

</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
      // Grid !
      var $container = $('.dashboard');

      $container.packery({
        itemSelector: '.panel',
        columnWidth: '.grid-sizer',
        gutter: '.grid-gutter'
      });
  });
</script>
