<form class="form-horizontal" action='<?php echo $this->url(array(), 'message_add', true) ?>' method='post' >

  <div class="modal-dialog">

      <div class="modal-content">

      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class='modal-title'>Ajouter un message</h3>
      </div>

      <div class="modal-body">

          <textarea id='textarea' class='form-control' name='text' style='margin-bottom: 20px;' rows='10' placeholder="Entrez ici votre message d'information."></textarea>

          <div class="form-group">
            <label class="col-sm-3 control-label">Confidentialité</label>
            <div class="col-sm-9">
              <select class='form-control' name="conf[]" multiple>
                <?php foreach($this->groupes as $groupe) : ?>
                <option value="<?php echo $groupe["ID_GROUPE"] ?>" selected><?php echo $groupe["LIBELLE_GROUPE"] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Type du message</label>
            <div class="col-sm-9">
              <select class='form-control' name="type">
                  <option>Message de service</option>
                  <option>Informations</option>
                  <option>Message personnel</option>
                  <option>Autre</option>
              </select>
            </div>
          </div>

      </div>

      <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Annuler</a>
          <input type='submit' id='submit' value='Ajouter' class='btn btn-success' />
      </div>

    </div>

  </div>

</form>

<script>
    $("select[name='conf[]']").multiselect({nonSelectedText: "Aucun groupement"});
</script>
