<h1 class="page-header">Statistiques et extractions</h1>

<form id="formulaire_stats" class="well form-horizontal">

	<select id="demande" class='form-control'>
		<option href="">Choisir des données à générer ...</option>
        <?php foreach($this->liste as $url => $titre) : ?>
            <option href="/statistiques/<?php echo $url ?>"><?php echo $titre ?></option>
        <?php endforeach ?>
	</select>

    <br>

    <div class='row-fluid'>

    	<div id="champssupps"></div>

        <div id="export-buttons" class="form-group form-group-sm hide">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="dropdown">
                    <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                        Exporter ... <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><a id="voir" href="#">Sous forme d'une liste</a></li>
                        <li><a id="export" href="#">Dans un fichier XML</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</form>

<p id="loading" class="hide" style="font-size: 3em; color: silver; text-align: center; margin-top: 100px;">
    Génération en cours ...<br>
    <img src="/assets/img/load.gif" />
</p>

<div id="results"></div>

<script>

    document.addEventListener('DOMContentLoaded', function() {

        $("#demande").change(function() {
            $("#champssupps").html(""); // on vide les champs supplémentaires
            $("#export-buttons").show(); // On disable les boutons

            var href = $(this).find("option:selected").attr("href");

            // On charge les champs supplémentaires
            if(href != "") {

                $.getJSON(href + "?format=json", function(data) {

                    // Si il n'y a pas de champs supplémentaire, on annule
                    if(data.result == undefined)
                        return;

                    $.each(data.result, function(key, val) {

                        // Création du label
                        var champ = "<div class='form-group'><label class='col-sm-2 control-label'>" + val.label + "</label><div class='col-sm-10'>";

                        // Création du champ en fonction du type
                        switch(val.type) {
                            case "select" :
                                champ += "<select class='form-control' name='" + key + "'>";
                                for(var labelOption in val.data) {
                                    champ += "<option value='" + val.data[labelOption] + "'>" + labelOption + "</option>";
                                }
                                champ += "</select>";
                                break;

                            case "date" :
                            case "datefin" :
                                champ += "<div style='width: 170px'><input class='form-control' type='date' name='" + key + "' value='" + val.data + "'  /></div>";
                                break;

                            case "id" :
                                break;

                            default :
                                alert("Type inconnu : " + val.type);
                                return;
                        }

                        champ += "<div></div>";

                        // On ajoute le champ
                        var oldhtml = $("#champssupps").html();
                        $("#champssupps").html( oldhtml + champ);

                    });

                });
            }
            else {
                $("#export-buttons").hide();
            }
        });

    	$("#voir").click(function() {
    		$.ajax({
    			url: $("#demande").find("option:selected").attr("href") + "?" + $("#formulaire_stats").serialize(),
    			beforeSend: function() {
    				$("#results").html("");
    				$("#loading").show();
    			},
    			success: function(data) {
    			$('.result').html(data);
    				$("#results").html(data);
    				$("#loading").hide();
    			}
    		});
    		return false;
    	});

    	$("#export").click(function() {
    		window.location.href = $("#demande").find("option:selected").attr("href") + "?" + "format=xml&" + $("#formulaire_stats").serialize();
    		return false;
    	});

    });

</script>
