<div class="col-xs-3">
    <?php if($this->document != null) : ?>
        <a href="#" class="thumbnail" style="height: 70px; text-align: center;">
            <strong><i class='glyphicon glyphicon-file'></i>  <?php echo $this->libelle ?></strong><br>
            <small><?php echo $this->document ?></small>
        </a>
    <?php else : ?>
        <p class="thumbnail muted" style="height: 70px; text-align: center;">
            <strong><i class='glyphicon glyphicon-file'></i>  <?php echo $this->libelle ?></strong><br>
            Aucun document
        </p>
    <?php endif ?>
</div>
