<?php if($this->etablissement) : ?>

<!-- Libelle -->
<h1>
  <!-- Parents -->
  <?php if( $this->etablissement['parents'] > 0 ) : ?>
      <?php foreach($this->etablissement['parents'] as $key => $etablissement) : ?>
          <?php echo "<a href='/etablissement/index/id/" . $etablissement["ID_ETABLISSEMENT"] . "'>" . $etablissement["LIBELLE_ETABLISSEMENTINFORMATIONS"] . "</a>"; ?>
          <?php if(true || $key != count($this->etablissement['parents']) - 1) : ?>
            <?php echo "<span class='muted'> &gt; </span>"; ?>
          <?php endif ?>
      <?php endforeach ?>
  <?php endif ?>

  <?php echo file_exists(APPLICATION_PATH . DS . '..' . DS . 'public' . DS . 'img' . DS . 'types' . DS . 'b' . DS . 'icone-type-' . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . '.png') ? "<img src='/img/types/b/icone-type-" . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . ".png' title='" . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . "' />" : ''; ?>
  <?php echo $this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"]." " ?>
</h1>

<p>

  <!-- Avis -->
  <?php if($this->etablissement['presence_avis_differe'] == true) : ?>
    <span class='avis avis-differe'>
        Présence d'un dossier avec avis differé
    </span>
    &nbsp;
  <?php elseif($this->etablissement['avis'] != null) : ?>
    <span class='avis <?php echo $this->etablissement['avis'] == 1 ? 'avis-favorable' : 'avis-defavorable' ?>'>
        <?php echo ($this->etablissement['avis'] == 1 ? 'Favorable' : 'Défavorable') . ($this->etablissement['informations']['ID_GENRE'] == 3 ? '' : " à l'exploitation ") ?>
        <?php if($this->etablissement['avis'] != 1 && $this->etablissement['facteur_dangerosite'] > 0) : ?>
        · Facteur de criticité : <?php echo $this->etablissement['facteur_dangerosite'] ?>
        <?php endif ?>
    </span>
    &nbsp;
  <?php endif ?>

  <!-- Présence d'un dossier échéancier de travaux -->
  <?php if($this->etablissement['presence_echeancier'] == true) : ?>
    <span class='label label-info'>
        Présence d'un échéancier de travaux
    </span>
    &nbsp;
  <?php endif ?>

  <!-- Statut -->
  <span>Statut : <?php echo $this->etablissement['informations']['LIBELLE_STATUT'] ?>&nbsp;</span>

  <!-- ID -->
  <?php if(!empty($this->etablissement['general']['NUMEROID_ETABLISSEMENT'])) : ?>
    <span class="pull-right"><small>id: <?php echo $this->etablissement['general']['NUMEROID_ETABLISSEMENT'] ?></small></span>
  <?php endif ?>

</p>

<hr>

<?php endif ?>
