<!-- Onglets permettant de selectionner les entités à rechercher -->
<h1 class="page-header">Etablissements</h1>

<form method='get'>

	<div class='well well-sm'>

		<div class="input-group col-xs-6 pull-left">
			<input type="text" name='label' class="form-control search-query" placeholder="Libellé de l'établissement ou son #ID ..." value='<?php if(isset($_GET["label"])) echo $_GET["label"] ?>' />
			<input type='hidden' name='page' value="1" />
			<span class="input-group-btn">
				<input type='submit' class="btn btn-primary" value="Rechercher dans Prevarisc" disabled />
			</span>
		</div>

		<div class='pull-right' style='margin: 8px 0 0 5px'>
			<small>
						Zone de recherche :
						<strong class='zone_de_recherche_text'>
							<?php echo array_key_exists('zone_de_recherche_text', $_GET) && $_GET['zone_de_recherche_text'] != '' ? $_GET['zone_de_recherche_text'] : 'Département' ?>
						</strong>
						<a href='#' onclick="$('#zone_de_recherche_modal').modal(); return false; ">(Modifier la zone de recherche)</a>
						<input type='hidden' name='zone_de_recherche_text' value="<?php if(array_key_exists('zone_de_recherche_text', $_GET)) echo $_GET['zone_de_recherche_text'] ?>" />
			</small>
		</div>

		<div style="clear: both"></div>

	</div>

	<div>
	    <select name='statuts[]' multiple>
	        <?php foreach( $this->DB_statut as $statut ) : ?>
	        	<option value='<?php echo $statut["ID_STATUT"] ?>' <?php if(isset($_GET["statuts"]) && in_array($statut["ID_STATUT"], (array) $_GET["statuts"])) echo 'selected' ?>><?php echo $statut["LIBELLE_STATUT"] ?></option>
	        <?php endforeach ?>
	    </select>

	    <select name='presences_local_sommeil[]' multiple>
        	<option value='true' <?php if(isset($_GET["presences_local_sommeil"]) && in_array('true', (array) $_GET["presences_local_sommeil"])) echo 'selected' ?>>Avec locaux à sommeil</option>
        	<option value='false' <?php if(isset($_GET["presences_local_sommeil"]) && in_array('false', (array) $_GET["presences_local_sommeil"])) echo 'selected' ?>>Sans locaux à sommeil</option>
	    </select>

	    <select name='avis[]' multiple>
        	<option value='true' <?php if(isset($_GET["avis"]) && in_array('true', (array) $_GET["avis"])) echo 'selected' ?>>Favorable</option>
        	<option value='false' <?php if(isset($_GET["avis"]) && in_array('false', (array) $_GET["avis"])) echo 'selected' ?>>Défavorable</option>
	    </select>
    </div>

    <div style='margin-top: 4px'>
			<select id='test' name='genres[]' multiple>
		        <?php foreach( $this->DB_genre as $genre ) : ?>
		        	<option value='<?php echo $genre["ID_GENRE"] ?>' <?php if(array_key_exists('genres', $_GET) && in_array($genre["ID_GENRE"], (array) $_GET["genres"])) echo 'selected' ?>><?php echo $genre["LIBELLE_GENRE"] ?></option>
		        <?php endforeach ?>
			</select>

			<span id='categorie_span' class='hide'>
				<select name='categories[]' multiple>
					<?php foreach( $this->DB_categorie as $categorie ) : ?>
			        <option value='<?php echo $categorie["ID_CATEGORIE"] ?>' <?php if(array_key_exists('categories', $_GET) && in_array($categorie["ID_CATEGORIE"], (array) $_GET["categories"])) echo 'selected' ?>><?php echo $categorie["LIBELLE_CATEGORIE"] ?></option>
			        <?php endforeach ?>
				</select>
			</span>

			<span id='classe_span' class='hide' >
		        <select name='classes[]' multiple>
		            <?php foreach( $this->DB_classe as $classe ) : ?>
		            	<option value='<?php echo $classe["ID_CLASSE"] ?>' <?php if(array_key_exists('classes', $_GET) && in_array($classe["ID_CLASSE"], (array) $_GET["classes"])) echo 'selected' ?>><?php echo $classe["LIBELLE_CLASSE"] ?></option>
		            <?php endforeach ?>
		        </select>
		    </span>

		    <span id='famille_span' class='hide'>
		    	<select name='familles[]' multiple>
		            <?php foreach( $this->DB_famille as $famille ) : ?>
		           		<option value='<?php echo $famille["ID_FAMILLE"] ?>' <?php if(array_key_exists('familles', $_GET) && in_array($famille["ID_FAMILLE"], (array) $_GET["familles"])) echo 'selected' ?>><?php echo $famille["LIBELLE_FAMILLE"] ?></option>
		            <?php endforeach ?>
		        </select>
		    </span>

		    <span id='type_span' class='hide'>
		        <select name='types[]' multiple>
		            <?php foreach( $this->DB_type as $type ) : ?>
		            	<option value='<?php echo $type["ID_TYPE"] ?>' <?php if(array_key_exists('types', $_GET) && in_array($type["ID_TYPE"], (array) $_GET["types"])) echo 'selected' ?>><?php echo $type["LIBELLE_TYPE"] ?></option>
		            <?php endforeach ?>
		        </select>
		  </span>
    </div>

		<!-- Boite modale de la zone de recherche -->
		<div id='zone_de_recherche_modal' class="modal form-horizontal">

			<div class="modal-dialog">

				<div class="modal-content">

					<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3>Définir la zone de recherche</h3>
					</div>

					<div class="modal-body">

						<div class="form-group">
							<label class="col-sm-3 control-label">Ville</label>
							<div class="col-sm-9">
								<select name='id_city' class='adresse_commune' placeholder='Nom de la commune ou code postal ...'>
								<?php if(array_key_exists('id_city', $_GET)) : ?>
									<option value='<?php echo $_GET['id_city'] ?>' selected>
										<?php echo $_GET['city'] ?>
									</option>
								<?php endif ?>
								</select>
								<input type='hidden' name='city' value='<?php if(array_key_exists('city', $_GET)) echo $_GET['city'] ?>' />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label">Voie</label>
							<div class="col-sm-9">
								<select name='id_street' class='adresse_voie' placeholder='Nom de la voie ...' <?php if(!array_key_exists('city', $_GET)) echo 'disabled' ?> >
									<?php if(array_key_exists('id_street', $_GET)) : ?>
										<option value='<?php echo $_GET['id_street'] ?>' selected>
											<?php echo $_GET['street'] ?>
										</option>
									<?php endif ?>
								</select>
								<input type='hidden' name='street' value='<?php if(array_key_exists('street', $_GET)) echo $_GET['street'] ?>' />
							</div>
						</div>

					</div>

					<div class="modal-footer">
							<a href="#" data-dismiss="modal" class="btn">Annuler</a>
							<a class='submit btn btn-success' >Définir la zone de recherche</a>
					</div>

				</div>

			</div>

		</div>

</form>

<hr/>

<?php if( count($this->results) > 0 ) : ?>
    <p class='muted'><small>Nombre total d'éléments : <?php echo $this->results->getTotalItemCount() ?></small></p>
    <ul class='search-list'>
    <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->results ) ?>
    </ul>
    <br/>
    <div style='clear: both'></div>
    <?php echo $this->results ?>
<?php else : ?>
	<p class='muted'><small>Aucun résultat disponible.</small></p>
    <h2 style='color: silver; text-align: center;' ></h2>
<?php endif ?>

<script>
  document.addEventListener('DOMContentLoaded', function() {

  	// Si le champ de recherche est vide, on empêche l'envoi d'une recherche
  	$("input[name='label']").focus().keyup(function() {$('input[type="submit"]').attr('disabled', $(this).val() == '')}).keyup();

		// Gestion des multiselects
		$("select[name='statuts[]']").multiselect({nonSelectedText: "Tous les statuts"});
		$("select[name='genres[]']").multiselect({nonSelectedText: "Tous les genres"});
		$("select[name='categories[]']").multiselect({nonSelectedText: "Toutes les catégories"});
		$("select[name='classes[]']").multiselect({nonSelectedText: "Toutes les classes"});
		$("select[name='familles[]']").multiselect({nonSelectedText: "Toutes les familles"});
		$("select[name='types[]']").multiselect({nonSelectedText: "Tous les types d'activités"});
		$("select[name='avis[]']").multiselect({nonSelectedText: "Tous les avis"});
		$("select[name='presences_local_sommeil[]']").multiselect({nonSelectedText: "Qu'importe la présence de local à sommeil", minWidth: 300});

		// Fonction d'affichage des critères en fonction du genre
		function display_criteres_by_genres() {
			$("#categorie_span, #classe_span, #famille_span, #type_span").hide();
			$("select[name='genres[]']").find('option:selected').each(function() {
				switch(this.value) {
					case '2' : $("#type_span, #categorie_span").show(); break;
					case '3' : $("#type_span, #categorie_span").show(); break;
					case '4' : $("#famille_span").show(); break;
					case '5' : $("#classe_span").show(); break;
				}
			});
		}

		// Affichage des critères en fonction du genre
		$("select[name='genres[]']").change(function() { display_criteres_by_genres(); });
		display_criteres_by_genres();

    // Auto complétion de la ville
		$("select.adresse_commune").selectize({
			valueField: 'id',
			labelField: 'name',
			searchField: 'name',
			load: function(query, callback) {
				if (!query.length) return callback();
				$.getJSON('/api/1.0/adresse/get_communes', {q: query}, function(data) {
					matches = [];
					$.map(data.response, function(item) {
						matches.push({ name: item.LIBELLE_COMMUNE, id: item.NUMINSEE_COMMUNE });
					});
					callback(matches);
				});
			},
			onChange: function(value) {
				if (value > 0) {
					$("select.adresse_voie")[0].selectize.enable();
					$("input[name='city']").val($("select.adresse_commune").next().find('.item').text());
				}
				else {
					$("select.adresse_voie")[0].selectize.disable();
					$("input[name='city']").val('');
				}
			},
			onDropdownOpen: function() {$(".selectize-dropdown.adresse_commune").stop().show();},
			onDropdownClose: function() {$(".selectize-dropdown.adresse_commune").stop().hide();}
		});

		// Autocomplétion de la rue
		$("select.adresse_voie").selectize({
			valueField: 'id',
			labelField: 'name',
			searchField: 'name',
			load: function(query, callback) {
				if (!query.length) return callback();
				$.getJSON('/api/1.0/adresse/get_voies', {code_insee: $("select[name='id_city'] option:selected").val(), q: query}, function(data) {
					matches = [];
					$.map(data.response, function(item) {
						matches.push({ name: item.LIBELLE_RUE, id: item.ID_RUE });
					});
					callback(matches);
				});
			},
			onChange: function(value) {
				if (value > 0) {
					$("input[name='street']").val($("select.adresse_voie").next().find('.item').text());
				}
				else {
					$("input[name='street']").val('');
				}
			},
			onDropdownOpen: function() {$(".selectize-dropdown.adresse_voie").stop().show();},
			onDropdownClose: function() {$(".selectize-dropdown.adresse_voie").stop().hide();}
		});

    // Validation de la zone de recherche
    $('#zone_de_recherche_modal a.submit').click(function() {

    	var text = 'Département';

    	if($("select.adresse_commune option:selected").val() > 0) {
    		var text = $("select.adresse_commune").next().find('.item').text();
    		if($("select.adresse_voie option:selected").val() > 0) {
    			var text = $("select.adresse_commune").next().find('.item').text() + ', ' + $("select.adresse_voie").next().find('.item').text();
    		}
    	}

			$("input[name='zone_de_recherche_text']").val(text);
			$(".zone_de_recherche_text").text(text);
			$('#zone_de_recherche_modal').modal('hide');

    });

	});
</script>
