<?php echo $this->render('commission/partials/header.phtml') ?>

<form id="competences" method='post'>

    <div class='pull-right' >
        <a class='btn btn-default' href="<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), 'comm_competences', true) ?>">Revenir sur l'affichage des compétences</a>
        <a href='<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), 'comm_competences_add', true) ?>' class="btn btn-primary" >Ajouter une ligne de compétence</a>
        <input type='submit' class="btn btn-success" value='Sauvegarder'>
    </div>

    <h2>Gestion des compétences</h2>

    <?php if(count($this->competences) == 0) : ?>

        <p class='muted'>Il n'y a pas de compétences.</p>

    <?php else : ?>

    <table class='table table-bordered table-hover'>
        <thead>
            <tr>
                <th rowspan="2">Zone de compétence</th>
                <th colspan="3">Compétences sur les ERP</th>
                <th>Compétences sur les IGH</th>
                <th>Compétences sur les dossiers</th>
                <th rowspan="2"></th>
            </tr>
            <tr>
                <th>Catégorie</th>
                <th>Type d'activité</th>
                <th>Local à sommeil</th>
                <th>Classe</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->competences as $competence) : ?>

            <input type='hidden' name='ID_REGLE[]' value='<?php echo $competence['id_regle'] ?>' />

            <tr>
                <td>
                    <?php if($this->commission['ID_COMMISSIONTYPE'] == 2) : ?>
                        <select name='<?php echo $competence['id_regle'] ?>_NUMINSEE_COMMUNE'>
                            <?php foreach($this->communes as $commune) : ?>
                                <option value="<?php echo $commune['NUMINSEE_COMMUNE'] ?>" <?php if( $commune['NUMINSEE_COMMUNE'] == $competence['commune']['LIBELLE_COMMUNE'] ) echo "selected" ?>><?php echo $commune['LIBELLE_COMMUNE'] ?></option>
                            <?php endforeach ?>
                        </select>
                    <?php else : ?>
                        <select name='<?php echo $competence['id_regle'] ?>_ID_GROUPEMENT' class='form-control'>
                            <?php foreach($this->groupements as $groupement) : ?>
                                <option value="<?php echo $groupement['ID_GROUPEMENT'] ?>" <?php if( $groupement['ID_GROUPEMENT'] == $competence['groupement']['ID_GROUPEMENT'] ) echo "selected" ?>><?php echo $groupement['LIBELLE_GROUPEMENTTYPE'] . ' - ' . $groupement['LIBELLE_GROUPEMENT'] ?></option>
                            <?php endforeach ?>
                        </select>
                    <?php endif ?>
                </td>
                <td>
                    <select name='<?php echo $competence['id_regle'] ?>_ID_CATEGORIE[]' class='select_categories' multiple>
                    <?php foreach($competence['categories'] as $categorie) : ?>
                        <option value='<?php echo $categorie['ID_CATEGORIE'] ?>' <?php if($categorie['ID_REGLE'] == $competence['id_regle']) echo "selected" ?>>
                            <?php echo $categorie['LIBELLE_CATEGORIE'] ?>
                        </option>
                    <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <select name='<?php echo $competence['id_regle'] ?>_ID_TYPE[]' class='select_classes' multiple>
                    <?php foreach($competence['types'] as $type) : ?>
                        <option value='<?php echo $type['ID_TYPE'] ?>' <?php if($type['ID_REGLE'] == $competence['id_regle']) echo "selected" ?>>
                            <?php echo $type['LIBELLE_TYPE'] ?>
                        </option>
                    <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <select name='<?php echo $competence['id_regle'] ?>_LOCALSOMMEIL[]' class='select_local_sommeil' multiple>
                        <option value="1" <?php if(in_array(1, $competence['local_sommeil'])) echo "selected" ?> >Avec</option>
                        <option value="0" <?php if(in_array(0, $competence['local_sommeil'])) echo "selected" ?> >Sans</option>
                    </select>
                </td>
                <td>
                    <select name='<?php echo $competence['id_regle'] ?>_ID_CLASSE[]' class='select_classes' multiple>
                    <?php foreach($competence['classes'] as $classe) : ?>
                        <option value='<?php echo $classe['ID_CLASSE'] ?>' <?php if($classe['ID_REGLE'] == $competence['id_regle']) echo "selected" ?>>
                            <?php echo $classe['LIBELLE_CLASSE'] ?>
                        </option>
                    <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <select name='<?php echo $competence['id_regle'] ?>_ETUDEVISITE[]' class='select_types_dossiers' multiple>
                        <option value="1" <?php if(in_array(1, $competence['etude_visite'])) echo "selected" ?> >Etude</option>
                        <option value="0" <?php if(in_array(0, $competence['etude_visite'])) echo "selected" ?> >Visite</option>
                    </select>
                </td>
                <td>
                    <a class="btn btn-danger" href="<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION'], 'id_competence' => $competence['id_regle']), 'comm_competences_delete', true)?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <?php endif ?>

</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {

        // Gestion des multiselects
        $("select.select_categories").multiselect({nonSelectedText: "Aucune catégorie", includeSelectAllOption: true, numberDisplayed: 0});
        $("select.select_types").multiselect({nonSelectedText: "Aucun type d'activité", includeSelectAllOption: true, numberDisplayed: 0});
        $("select.select_local_sommeil").multiselect({nonSelectedText: "Aucun critère sur les locaux à sommeil", includeSelectAllOption: true});
        $("select.select_classes").multiselect({nonSelectedText: "Aucune classe", includeSelectAllOption: true, numberDisplayed: 0});
        $("select.select_types_dossiers").multiselect({nonSelectedText: "Aucun type de dossier", includeSelectAllOption: true});

        // Autocomplete de la commune
        $("select[name='NUMINSEE_COMMUNE']").selectize({
            onDropdownOpen: function() {$("select[name='NUMINSEE_COMMUNE']").next().find(".selectize-dropdown").stop().show();},
            onDropdownClose: function() {$("select[name='NUMINSEE_COMMUNE']").next().find(".selectize-dropdown").stop().hide();}
        });

        // S'affranchir du post-limit
        $('form#competences').submit(function() {
            $('input[name="multiselect"]').remove();
            $(this).find("input[type='submit']").attr('disabled', true);
            $.post( "<?php echo $this->url() ?>", $(this).serialize(), function() {
                window.location = "<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), 'comm_competences', true) ?>";
            });
            return false;
        });

    });
</script>
