<?php echo $this->render('commission/partials/header.phtml') ?>

<div class='pull-right' >
    <a class='btn btn-default' href="<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), 'comm_membres_edit', true) ?>">Modifier les membres types</a>
</div>

<h2>Membres types</h2>

<?php if(count($this->membres) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de membre.</p>
        <p><a href='<?php echo $this->url(array('id' => $this->commission['ID_COMMISSION']), 'comm_membres_edit', true) ?>' class='btn btn-default btn-large'>Gérer les membres types</a></p>
    </div>

<?php else : ?>

<table class='table table-bordered table-hover'>
    <thead>
        <tr>
            <th rowspan="2">Libellé du membre</th>
            <th rowspan="2">Zone de compétence</th>
            <th colspan="2">Compétences sur les ERP</th>
            <th>Compétences sur les IGH</th>
            <th>Compétences sur les dossiers</th>
        </tr>
        <tr>
            <th>Catégorie</th>
            <th>Type d'activité</th>
            <th>Classe</th>
            <th>Nature</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->membres as $membre) : ?>
        <tr>
            <td>
                <strong><?php echo $membre['libelle'] == null ? 'Pas de libellé' : $membre['libelle'] ?></strong>

                <small class='muted'>
                    <?php if($membre['presence'] == 0) : ?>
                        Membre obligatoire
                    <?php elseif($membre['presence'] == 1) : ?>
                        Membre facultatif
                    <?php elseif($membre['presence'] == 2) : ?>
                        Membre pour information
                    <?php endif ?>
                </small>
            </td>
            <td>
                <?php if($membre['contact'] != null) : ?>
                    Contact de la commission : <?php echo $membre['contact']['NOM_UTILISATEURINFORMATIONS'] . ' ' . $membre['contact']['PRENOM_UTILISATEURINFORMATIONS'] ?>
                <?php elseif($membre['groupement'] != null) : ?>
                    Groupement de communes : <?php echo $membre['groupement']['LIBELLE_GROUPEMENT'] . ' (' . $membre['groupement']['LIBELLE_GROUPEMENTTYPE'] . ')' ?>
                <?php else : ?>
                    Commune du dossier
                <?php endif ?>
            </td>
            <td>
                <ul class='list-inline'>
                <?php foreach($membre['categories'] as $categorie) : ?>
                    <?php if($categorie['ID_COMMISSIONMEMBRE'] == $membre['id_membre']) : ?>
                        <li><?php echo $categorie['LIBELLE_CATEGORIE'] ?></li>
                    <?php endif ?>
                <?php endforeach ?>
                </ul>
            </td>
            <td>
                <dl class='dl-horizontal'>
                <?php foreach($membre['types'] as $type => $activites) : ?>
                    <dt><?php echo $type ?></dt>
                    <dd>
                        <ul class='list-inline'>
                        <?php foreach($activites as $activite) : ?>
                            <?php if($activite['ID_COMMISSIONMEMBRE'] == $membre['id_membre']) : ?>
                                <li><?php echo $activite['LIBELLE_ACTIVITE'] ?></li>
                            <?php endif ?>
                        <?php endforeach ?>
                        </ul>
                    </dd>
                <?php endforeach ?>
                </dl>
            </td>
            <td>
                <ul class='list-inline'>
                <?php foreach($membre['classes'] as $classe) : ?>
                    <?php if($classe['ID_COMMISSIONMEMBRE'] == $membre['id_membre']) : ?>
                        <li><?php echo $classe['LIBELLE_CLASSE'] ?></li>
                    <?php endif ?>
                <?php endforeach ?>
                </ul>
            </td>
            <td>
                <dl class='dl-horizontal'>
                <?php foreach($membre['dossiertypes'] as $type) : ?>
                    <dt><?php echo $type['LIBELLE_DOSSIERTYPE'] ?></dt>
                    <dd>
                        <ul class='list-inline'>
                        <?php foreach($membre['dossiernatures'] as $nature) : ?>
                            <?php if($type['ID_DOSSIERTYPE'] == $nature['ID_DOSSIERTYPE'] && $nature['ID_COMMISSIONMEMBRE'] == $membre['id_membre']) : ?>
                                <li><?php echo $nature['LIBELLE_DOSSIERNATURE'] ?></li>
                            <?php endif ?>
                        <?php endforeach ?>
                        </ul>
                    </dd>
                <?php endforeach ?>
                </dl>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php endif ?>

<script>
    document.addEventListener('DOMContentLoaded', function() {

        // Juste une amélioration visuelle o/
        $('table tbody tr').each(function(tr_key) {

            $(this).find('td').each(function(td_key) {

                switch(td_key) {
                    case 2: if($(this).find('li').length == 5) $(this).text('Toutes les catégories'); break;
                    case 3: if($(this).find('li').length == 110) $(this).text('Tous les types d\'activité'); break;
                    case 4: if($(this).find('li').length == 10) $(this).text('Toutes les classes IGH'); break;
                    case 5: if($(this).find('li').length == 48) $(this).text('Toutes les natures'); break;
                }

                if($(this).find('ul.list-inline').length == 1) {
                    if($(this).find('ul.list-inline').find('li').length == 0) {
                        $(this).css('background-color', '#f5f5f5');
                    }
                }
                if($(this).find('dl.dl-horizontal').length == 1) {
                    $(this).find('dl.dl-horizontal').find('dd').each(function() {
                        if($(this).find('ul.list-inline').find('li').length == 0) {
                            $(this).prev().remove();
                            $(this).remove();
                        }
                    });
                    if($(this).find('dl.dl-horizontal dt').length == 0) {
                        $(this).css('background-color', '#f5f5f5');
                    }
                }
                else if($(this).text().trim() == "") {
                    $(this).css('background-color', '#f5f5f5');
                }
            });

        });

    });
</script>
